apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      greymatter.io/control: {{ .Values.name }}
      deployment: {{ .Values.name }}
  replicas: 1
  template:
    metadata:
      labels:
        greymatter.io/control: {{ .Values.name }}
        deployment: {{ .Values.name }}
    spec:
      containers:
        - name: sidecar
          image: {{ tpl $.Values.sidecar.image $ | quote }}
          imagePullPolicy: {{ .Values.sidecar.imagePullPolicy | quote }}
          env:
          {{- include "envvars" (dict "envvar" .Values.sidecar.envvars "top" $) | indent 12 }}
            {{- if .Values.global.spire.enabled }}
            - name: SPIRE_PATH
              value: {{ .Values.global.spire.path }}
            {{- end }}
          ports:
          - containerPort: {{ .Values.sidecar.port }}
            protocol: TCP
            name: proxy
          - containerPort: {{ .Values.sidecar.metrics_port }}
            protocol: TCP
            name: metrics
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/proxy/tls/sidecar
              name: sidecar-certs
            {{- if .Values.global.spire.enabled }}
            - name: spire-socket
              mountPath: /run/spire/socket
              readOnly: false
            {{- end }}
      dnsPolicy: ClusterFirst
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
        - name: sidecar-certs
          secret:
            defaultMode: 420
            optional: false
            secretName: sidecar-certs
        {{- if .Values.global.spire.enabled }}
        - name: spire-socket
          hostPath:
            path: /run/spire/socket
            type: DirectoryOrCreate
        {{- end }}
