apiVersion: v1
kind: Service
metadata:
  name: registrar
  namespace: {{ .Values.global.spire.namespace }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
spec:
  ports:
    - name: registrar
      protocol: TCP
      port: 8444
      targetPort: registrar
  selector:
    app: server
