apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: server
  namespace: {{ .Values.global.spire.namespace }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
subjects:
  - kind: ServiceAccount
    name: server
    namespace: {{ .Values.global.spire.namespace }}
roleRef:
  kind: Role
  name: server
  apiGroup: rbac.authorization.k8s.io
