apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: {{ .Values.global.spire.namespace }}
spec:
  type: NodePort
  ports:
    - name: server
      port: 8443
      targetPort: server
      protocol: TCP
  selector:
    app: server
