{{- $intCA := "" -}}
{{- $rootCA_b64 := "" -}}
{{- $certChain_b64 := "" -}}
{{- $namespace := (printf "%s" .Values.global.spire.namespace) -}}
{{- if .Values.global.spire.auto_generate_ca_certs -}}
# Auto-generate CA certs
{{- $intCA = genCA "root-ca" 3650 -}}
{{- $rootCA_b64 = $intCA.Cert | b64enc -}}
{{- $certChain_b64 = $intCA.Cert | b64enc -}}
{{- else -}}
# Use provided CA certs
{{- $intCA = buildCustomCert .Values.global.spire.ca_certificates.int_ca_crt_b64enc .Values.global.spire.ca_certificates.int_ca_key_b64enc -}}
{{- $rootCA_b64 = .Values.global.spire.ca_certificates.root_ca_crt_b64enc -}}
{{- $certChain_b64 = .Values.global.spire.ca_certificates.cert_chain_b64enc -}}
{{- end -}}
{{- $cert := genSignedCert (printf "registrar.%s.svc" $namespace) (list "127.0.0.1") (list "localhost" (printf "registrar.%s.svc" $namespace)) (int .Values.global.spire.registrar_cert_valid_days) $intCA -}}
---
apiVersion: v1
data:
  intermediate.crt: {{ $intCA.Cert | b64enc | quote }}
  intermediate.key: {{ $intCA.Key | b64enc | quote }}
  root.crt: {{ $rootCA_b64 | quote }}
kind: Secret
metadata:
  creationTimestamp: null
  name: server-ca
  namespace: {{ $namespace }}
---
apiVersion: v1
data:
  ca.crt: {{ $certChain_b64 | quote }}
  {{ printf "registrar.%s.svc.crt" $namespace }}: {{ $cert.Cert | b64enc | quote }}
  {{ printf "registrar.%s.svc.key" $namespace }}: {{ $cert.Key | b64enc | quote }}
kind: Secret
metadata:
  creationTimestamp: null
  name: server-tls
  namespace: {{ $namespace }}
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: registrar
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
webhooks:
  - name: registrar.{{ $namespace }}.svc.cluster.local
    clientConfig:
      service:
        name: registrar
        namespace: {{ $namespace }}
        path: "/validate"
        port: 8444
      caBundle: {{ $certChain_b64 | quote }}
    admissionReviewVersions:
      - v1beta1
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - "v1"
        operations:
          - "CREATE"
          - "DELETE"
        resources:
          - "pods"
        scope: "Namespaced"