apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spire:server
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
subjects:
  - kind: ServiceAccount
    name: server
    namespace: {{ .Values.global.spire.namespace }}
roleRef:
  kind: ClusterRole
  name: spire:server
  apiGroup: rbac.authorization.k8s.io
