apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: {{ .Values.global.spire.namespace }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
spec:
  type: NodePort
  ports:
    - name: server
      port: 8443
      targetPort: server
      protocol: TCP
  selector:
    app: server
