apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: server
  namespace: {{ .Values.global.spire.namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - patch
      - get
      - list
