apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: greymatter-server
  namespace: {{ .Values.global.spire.namespace }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - patch
      - get
      - list
