apiVersion: v2
appVersion: 1.2.0
description: A Helm chart to deploy Grey Matter JWT Security
name: jwt
version: 3.0.4
home: https://greymatter.io
icon: https://s3.amazonaws.com/decipher-public/grey-matter/branding/grey-matter-mark-rgb.png
maintainers:
  - name: greymatter-io
    email: engineering@greymatter.io
keywords:
  - Grey Matter
  - service mesh
