xds:
  image: 'docker.production.deciphernow.com/deciphernow/gm-xds:0.2.6'  
  imagePullPolicy: Always
  version: 0.2.6
  cluster: greymatter
  #host: 'xds.greymatter.svc.cluster.local'
  port: 18000
  use_zk: 'true'
  logging_level: info
  zk_base_path: '/services'

sidecar:
  version: 0.7.1
  image: 'docker.production.deciphernow.com/deciphernow/gm-proxy:0.7.1'
  proxy_dynamic: 'true'
  metrics_key_function: depth
  ingress_use_tls: 'true'
  imagePullPolicy: Always

  # Set this to true if you are attempting to deploy Catalog by itself.  
  # Ideally, catalog is deployed as a dependency to Grey Matter, which creates the 
  # sidecar secret, but if individual testing is being done, the sidecar secret will
  # need to be created.  
  create_sidecar_secret: false
  certificates:
    # name: sidecar
    # ca: |-
    #   -----BEGIN CERTIFICATE-----
    #   ...
    #   -----END CERTIFICATE-----
    # cert: |-
    #   -----BEGIN CERTIFICATE-----
    #   ...
    #   -----END CERTIFICATE-----
    # key: |-
    #   -----BEGIN RSA PRIVATE KEY-----
    #   ...
    #   -----END RSA PRIVATE KEY-----


exhibitor:
  replicas: 1