# Redis Defaults

global:
  image_pull_secret: docker.secret
  # Deployment environment, one of "eks", "kubernetes", or "openshift"
  environment: kubernetes
  control:
    # The label Control uses to find pods to include in the mesh
    cluster_label: greymatter.io/control

redis:
  name: mesh-redis
  image: bitnami/redis:5.0.12
  replica_count: 1
  image_pull_policy: IfNotPresent
  # Uses global.image_pull_secret if true
  private_image: false
  command:
    - "redis-server"
  args:
    - "--appendonly"
    - "yes"
    - "--requirepass"
    - "$(REDIS_PASSWORD)"
    - "--dir"
    - "/data"
  secret:
    secret_name: greymatter-mesh-redis-password
  storage:
    # Where your redis image will place its data
    mount_path: /data
    # Size, in Gi, that the Redis PVC should be
    size: 40
  container_port: '6379'
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 128Mi
  # securityContext specifies the user and groups to use.  This needs needs to be turned on when deploying into openshift
  securityContext: {}
    # runAsUser: 2001
    # runAsGroup: 2001
    # fsGroup: 2001

  envvars:
    redis_password:
      type: secret
      secret: '{{ .Values.redis.secret.secret_name | default "greymatter-mesh-redis-password" }}'
      key: password
