# Redis Defaults

global:
  image_pull_secret: docker.secret
  # Deployment environment, one of "eks", "kubernetes", or "openshift"
  environment: eks
  control:
    # The label Control uses to find pods to include in the mesh
    cluster_label: greymatter.io/control

redis:
  name: mesh-redis
  # Redis image to use when global.environment=openshift
  openshift:
    image: 'centos/redis-32-centos7'
  # Redis image to use when global.environment=kubernetes
  k8s:
    image: 'redis:3.2'
  replica_count: 1
  image_pull_policy: IfNotPresent
  # Uses global.image_pull_secret if true
  private_image: false
  storage:
    # Where your redis image will place its data
    mount_path: /data
    # Size, in Gi, that the Redis PVC should be
    size: 40
  container_port: '6379'
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 128Mi
