# Redis Defaults

global:
  image_pull_secret: docker.secret
  # Deployment environment, one of "eks", "kubernetes", or "openshift"
  environment: eks
  control:
    # The label Control uses to find pods to include in the mesh
    cluster_label: greymatter.io/control

redis:
  name: mesh-redis
  image: 'redis:3.2'
  replica_count: 1
  image_pull_policy: IfNotPresent
  # Uses global.image_pull_secret if true
  private_image: false
  secret:
    secret_name: greymatter-mesh-redis-password
  storage:
    # Where your redis image will place its data
    mount_path: /data
    # Size, in Gi, that the Redis PVC should be
    size: 40
  container_port: '6379'
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 128Mi
  envvars:
    redis_password:
      type: secret
      secret: '{{ .Values.redis.secret.secret_name | default "greymatter-mesh-redis-password" }}'
      key: password
