apiVersion: v2
appVersion: 1.2
description: A Helm chart to deploy Grey Matter Fabric
name: fabric
version: 3.0.0
icon: https://s3.amazonaws.com/decipher-public/grey-matter/branding/grey-matter-mark-rgb.png
maintainers:
  - name: Decipher Technology Studios Engineering
    email: engineering@deciphernow.com
    website: deciphernow.com
keywords:
  - Grey Matter
  - service mesh
  - fabric
dependencies:
  - name: gm-control-api
    repository: file://./gm-control-api
    version: '2.1.6'

  - name: control
    repository: file://./control
    version: '2.1.4'
