apiVersion: v2
appVersion: 1.2
description: A Helm chart to deploy Grey Matter Fabric
name: fabric
version: 2.2.0
icon: https://s3.amazonaws.com/decipher-public/grey-matter/branding/grey-matter-mark-rgb.png
maintainers:
  - name: Decipher Technology Studios Engineering
    email: engineering@deciphernow.com
    website: deciphernow.com
keywords:
  - Grey Matter
  - service mesh
  - fabric
dependencies:
  - name: control-api
    repository: file://./control-api
    version: '2.2.0'

  - name: control
    repository: file://./control
    version: '2.2.0'
    
  - name: jwt
    repository: file://./jwt
    version: '2.2.0'

  - name: jwt
    repository: file://./jwt
    version: '2.2.0'
    alias: internal-jwt