# Grey Matter Fabric Chart Overrides

global:
  image_pull_secret: docker.secret    # Used as imagePullSecrets value for each subchart
  environment: openshift              # Deployment environment, one of "eks", "kuberenetes", or "openshift"
  zone: zone-default-zone             # Used to configure control and control-api environment variables

control:
  control:
    secret:                           # Configures the secret for control to talk to control api via tls
      secret_name: controlapitls
      mountPoint: /service-certs
      insecure: true
      secretKeys:
        cert: server.crt
        key: server.key
    serviceAccount:
      create: true
    image: docker-dev.production.deciphernow.com/deciphernow/gm-control:latest
    envvars:
      gm_control_console_level:
        type: 'value'
        value: 'info'
      #gm_control_cmd:
      #  type: 'value'
      #  value: 'consul'
      #gm_control_consul_dc:
      #  type: 'value'
      #  value: 'dc1'
      #gm_control_consul_hostport:
      #  type: 'value'
      #  value: '{{ .Values.global.consul.host }}:{{ .Values.global.consul.port }}'

control-api:
  controlApi:
    secret:
      secret_name: controlapitls
      mountPoint: /service-certs
      insecure: true
    image: 'docker-dev.production.deciphernow.com/deciphernow/control-api:latest'
    zone: '{{ .Values.global.zone }}'
    init:
      image: docker-dev.production.deciphernow.com/deciphernow/greymatter:latest
  sidecar:
    image: 'docker-dev.production.deciphernow.com/deciphernow/gm-proxy:latest'