apiVersion: v2
appVersion: 1.6.0
description: A Helm chart to deploy the Spire Agent
name: agent
version: 4.0.0
home: https://greymatter.io
icon: https://s3.amazonaws.com/decipher-public/grey-matter/branding/grey-matter-mark-rgb.png
maintainers:
  - name: greymatter-io
    email: engineering@greymatter.io
keywords:
  - Grey Matter
  - service mesh
  - spire
  - agent
