global:
  control:
    cluster_label: greymatter.io/control
  spire:
    trust_domain: quickstart.greymatter.io
    namespace: spire
  environment: kubernetes

agent:
  name: agent
  image: gcr.io/spiffe-io/spire-agent:0.9.3
  private_image: false
  init_image: gcr.io/spiffe-io/wait-for-it
