kind: Deployment
apiVersion: apps/v1
metadata:
  name: slo
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      gmproxy: slo
      deployment: slo
  replicas: 1
  template:
    metadata:
      labels:
        gmproxy: slo
        deployment: slo
    spec:
      {{- if and .Values.global.environment (ne .Values.global.environment "openshift") }}
      securityContext:
        runAsUser: 2000
        runAsGroup: 0
        fsGroup: 2000
      {{- end }}
      serviceAccountName: {{ .Values.global.waiter.service_account.name }}
      {{- if not .Values.postgres.rds.enabled }}
      initContainers:
        - name: ensure-postgres
          image: {{ .Values.global.waiter.image }}
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: SERVICE
              value: postgres-slo
            - name: POST_DELAY
              value: "3"
      {{- end }}
      containers:
      - name: slo
        image: {{ tpl .Values.slo.image . }}
        imagePullPolicy: {{ .Values.slo.image_pull_policy }}
        {{- if .Values.slo.resources }}
        resources:
{{ toYaml .Values.slo.resources | indent 10 }}
        {{- end }}
        volumeMounts:
          {{- if .Values.postgres.secret.enabled }}
        - name: postgres-certs
          mountPath: {{ .Values.postgres.secret.mount_point }}
          {{- end}}
          {{- if .Values.slo.secret.enabled }}
        - name: service-certs
          mountPath: {{ .Values.slo.secret.mount_point }}
          {{- end }}
        env:        
        {{- include "envvars" (dict "envvar" .Values.slo.envvars "top" $) | indent 10 }}
        # Because of the order of envvars is not guaranteed when templating, we are hardcoding database_uri as the last envvar
        # https://github.com/kubernetes/kubernetes/issues/40373
          - name: DATABASE_URI
          {{- if .Values.postgres.rds.enabled }}
            value: postgres://$(POSTGRESQL_USERNAME):$(POSTGRESQL_PASSWORD)@$(POSTGRESQL_ENDPOINT):5432/$(POSTGRESQL_DATABASE)
          {{- else }}
            value: postgres://$(POSTGRESQL_USERNAME):$(POSTGRESQL_PASSWORD)@postgres-slo.{{ .Release.Namespace }}.svc:5432/$(POSTGRESQL_DATABASE)
          {{- end }}
      - name: sidecar
        image: {{ tpl .Values.sidecar.image $ | quote }}
        imagePullPolicy: {{ .Values.sidecar.image_pull_policy }}
        {{- if .Values.sidecar.resources }}
        resources:
{{ toYaml .Values.sidecar.resources | indent 10 }}
        {{- end }}
        ports:
        - name: proxy
          containerPort: 10808
        - name: metrics
          containerPort: 8081
        env:
        {{- include "sidecar.envvars" . | indent 8 }}
        {{- if .Values.sidecar.secret.enabled }}
        volumeMounts:
        {{- include "sidecar_volume_certs_mount" . | indent 8 }}
        {{- end }}
      {{- if .Values.global.consul.enabled }}
      {{- $data := dict "Values" .Values "ServiceName" "slo" }}
      {{- include "consul.agent" $data | nindent 6 }}
      {{- end }}
      imagePullSecrets:
        - name: {{ .Values.global.image_pull_secret }}
      volumes:
      {{- if .Values.sidecar.secret.enabled }}
      {{- include "sidecar_certs_volumes" . | indent 6 }}
      {{- end }}
      {{- if .Values.postgres.secret.enabled }}
      - name: postgres-certs
        secret:
          secretName: {{ .Values.postgres.secret.secret_name }}
      {{- end }}
      {{- if .Values.slo.secret.enabled }}
      - name: service-certs
        secret:
          secretName: {{ .Values.slo.secret.secret_name }}
      {{- end }}
      {{- if .Values.global.consul.enabled }}
      - name: data-consul
        emptyDir: {}
      - name: config-consul
        emptyDir: {}
      {{- end }}
