apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Values.controlApi.name}}-init
  annotations:
    # Run this job after an install or an upgrade
    "helm.sh/hook": post-install,post-upgrade
    # If a job with this name already exists, delete it before running this one
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: {{ .Values.controlApi.name}}-init
    spec:
      restartPolicy: "Never"
      # We need a SA with read access to the `Endpoints` resource
      serviceAccountName: {{ .Values.global.waiter.service_account.name }}
      initContainers:
        - name: ensure-gm-control-api
          image: {{ .Values.global.waiter.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: SERVICE
              value: {{ .Values.controlApi.name }}
        {{- if .Values.global.external_redis.disabled }}        
        - name: ensure-mesh-redis
          image: {{ .Values.global.waiter.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: SERVICE
              value: {{ .Values.mesh_redis.name }}
        {{- end }}
      containers:
        - image: {{ tpl .Values.bootstrap.image . }}
          name: {{ .Values.controlApi.name }}-init
          imagePullPolicy: {{ .Values.bootstrap.image_pull_policy }}
          command: ["/tmp/bootstrap/bootstrap.sh"]
          env:
          {{- include "envvars" (dict "envvar" .Values.bootstrap.envvars "top" $) | indent 10 }}
          volumeMounts:
            {{- if .Values.controlApi.secret }}
            - name: service-certs
              mountPath: {{ .Values.bootstrap.secret.mount_point }}
            {{- end }}
          {{- $data := .Values.global.data.external.enabled }}
          {{- range $name, $service := .Values.services }}
          {{- if and (eq .serviceName "data") (not $data) }}
          {{- else if $service.controlEnabled }}
            - name: service-config-volume-{{$service.serviceName}}
              mountPath: /etc/config/mesh/services/{{$service.serviceName}}
            - name: edge-config-volume-{{$service.serviceName}}
              mountPath: /etc/config/mesh/edge/{{$service.serviceName}}
          {{- end }}
          {{- end }}
            - name: special-config-volume
              mountPath: /etc/config/mesh/special
            - name: bootstrap-script-volume
              mountPath: /tmp/bootstrap
      volumes:
        {{- if .Values.controlApi.secret }}
        - name: service-certs
          secret:
            {{- if .Values.global.global_certs.enabled }}
            secretName: global-certs
            {{- else }}
            secretName: {{ .Values.bootstrap.secret.secret_name }}
            {{- end }}
        {{- end }}
        {{- $data := .Values.global.data.external.enabled }}
        {{- range $name, $service := .Values.services }}
        {{- if and (eq .serviceName "data") (not $data) }}
        {{- else if $service.controlEnabled }}
        - name: service-config-volume-{{ $service.serviceName }}
          configMap:
            name: service-{{ $service.serviceName }}-mesh-config
        - name: edge-config-volume-{{ $service.serviceName }}
          configMap:
            name: edge-{{ $service.serviceName }}-mesh-config
        {{- end }}
        {{- end }}
        - name: bootstrap-script-volume
          configMap:
            name: bootstrap-script
            defaultMode: 0777
        - name: special-config-volume
          configMap:
            name: special-mesh-config
      imagePullSecrets:
        - name: {{ .Values.global.image_pull_secret }}
