kind: ConfigMap
apiVersion: v1
metadata:
  name: domain-config
  namespace: {{ .Release.Namespace }}
data:
  domain1.json: |-
{{ .Files.Get "config/domain.json" | indent 4 }}
  domain2.json: |-
{{ .Files.Get "config/domain2.json" | indent 4 }}