# Default values for gm-control-api.
global:
  environment: kubernetes
  domain:
  route_url_name:
  control_api_tls: true
  remove_namespace_from_url: ''
  exhibitor:
    replicas: 1
  # XDS will be replaced with gm-control
  xds:
    port: 18000
    cluster: greymatter
  gmControlApi:
    version: 1.1.0
    cli:
      version: 1.1.0
  data:
    data_prefix: '/data'
    jwt_prefix: '/jwt'
  waiter:
    image: deciphernow/k8s-waiter:latest
  consul:
    enabled: false
    host: ''
    port: 8500

gmControlApi:
  name: gm-control-api
  displayName: gm-control-api
  replicas: 1
  image: 'docker.production.deciphernow.com/deciphernow/gm-control-api:{{ $.Values.global.gmControlApi.version }}'
  imagePullPolicy: IfNotPresent
  containerPort: 5555
  zone: 'zone-default-zone'
  proxyPort: 8080
  pvcMountPoint: '/app/control-api/data/backend.json'
  ssl:
    name: control-api-certs
    mountPoint: /service-certs
    insecure: true
    certificates:
      ca: |-
        -----BEGIN CERTIFICATE-----
        ...
        -----END CERTIFICATE-----
      cert: |-
        -----BEGIN CERTIFICATE-----
        ...
        -----END CERTIFICATE-----
      key: |-
        -----BEGIN RSA PRIVATE KEY-----
        ...
        -----END RSA PRIVATE KEY-----
  init:
    image: 'docker.production.deciphernow.com/deciphernow/greymatter:{{ $.Values.global.gmControlApi.cli.version }}'
    imagePullPolicy: IfNotPresent
    envvars:
      greymatter_console_level:
        value: 'debug'
        type: 'value'
      greymatter_api_host:
        value: '{{ .Values.gmControlApi.name }}:{{ .Values.gmControlApi.containerPort }}'
        type: 'value'
      greymatter_api_key:
        value: 'xxx'
        type: 'value'
      greymatter_api_ssl:
        value: 'false'
        type: 'value'
      basic_object_path:
        value: '/tmp/mesh/basic_objects'
        type: 'value'
  envvars:
    gm_control_api_log_level:
      type: 'value'
      value: 'debug'
    gm_control_api_address:
      type: 'value'
      value: '0.0.0.0:5555'
    gm_control_api_org_key:
      type: 'value'
      value: 'deciphernow'
    gm_control_api_zone_key:
      type: 'value'
      value: 'zone-default-zone'
    gm_control_api_zone_name:
      type: 'value'
      value: 'zone-default-zone'
    gm_control_api_persister_type:
      type: value
      value: 'file'
    gm_control_api_persister_path:
      type: value
      value: '{{ .Values.gmControlApi.pvcMountPoint }}'
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 500m
    #   memory: 1Gi
    # requests:
    #   cpu: 250m
    #   memory: 256Mi
  pvc:
    #  We  default the PVC to 1Gi, but if more is desired, uncomment this line and update the size
    size:

sidecar:
  version: '{{- $.Values.global.catalog.sidecar.version | default "1.0.0" }}'
  image: 'docker.production.deciphernow.com/deciphernow/gm-proxy:{{ tpl $.Values.sidecar.version $ }}'
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  envvars:
    xds_cluster:
      type: value
      value: 'gm-control-api'
