apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.documentation.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.documentation.name }}
      deployment: {{ .Values.documentation.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.documentation.name }}
        deployment: {{ .Values.documentation.name }}
    spec:
      containers:
        - name: {{ .Values.documentation.name }}
          image: {{ tpl .Values.documentation.image $ | quote }}
          imagePullPolicy: {{ .Values.documentation.imagePullPolicy }}
          env:
      {{- range $envvar := .Values.documentation.envvars }}
        {{- $envName := $envvar.name | upper | replace "." "_" | replace "-" "_" }}
          {{- if eq $envvar.type "secret" }}
          - name: {{ $envName }}
            valueFrom:
              secretKeyRef:
                name: {{ $envvar.secret }}
                key: {{ $envvar.key }}
          {{- else if eq $envvar.type "value" }}
          - name: {{ $envName }}
            value: {{ tpl $envvar.value $ | quote }}
          {{- end }}
      {{- end  }} 
          ports:
            - containerPort: 8080
              name: http


        - name: sidecar
          image: {{ tpl $.Values.sidecar.image $ }}
          imagePullPolicy: Always
          env:
          {{- include "greymatter.envvars" . | indent 10 }}
          - name: XDS_CLUSTER
            value: {{ .Values.global.xds.cluster | quote }}
          - name: XDS_HOST
            value: "xds.{{ .Release.Namespace }}.svc.cluster.local"
          - name: XDS_PORT
            value: {{ .Values.global.xds.port | quote }}
          - name: ZK_ADDRS
            value: {{ template "greymatter.exhibitor.address" . }}
          - name: ZK_ANNOUNCE_PATH
            value: {{ tpl .Values.documentation.base_path $ }}

          ports:
            - containerPort: 8080
              name: http-port
              protocol: TCP
            - containerPort: 8443
              name: https-port
              protocol: TCP
            - containerPort: 8081
              name: metrics
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: sidecar
              mountPath: /etc/proxy/tls/sidecar
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: docker.secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: sidecar
          secret:
            secretName: sidecar