kind: Service
apiVersion: v1
metadata:
  name: exhibitor
  namespace: {{ .Release.Namespace }}
  labels:
    app: exhibitor
spec:
  ports:
  - name: client
    port: 2181
  - name: server
    port: 2888
  - name: election
    port: 3888
  - name: exhibitor
    port: 8080
  clusterIP: None
  selector:
    app: exhibitor
