apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: greymatter
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "https"
spec:
  rules:
    -
      http:
        paths:
          - path: /
            backend:
              serviceName: edge
              servicePort: 10808
