{{ if not .Values.global.global_certs.enabled }}
{{- if .Values.global.control_api_tls }}
{{ if .Values.control.controlApiTLS.certificates }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.control.controlApiTLS.name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
{{- if .Values.control.controlApiTLS.certificates.from_file.enabled }}
  {{- $fromfile := $.Values.control.controlApiTLS.certificates.from_file.path }}

  {{- $cacert := .Files.Get (include "cert" (dict "path" $fromfile "file" "ca.crt") ) }}
  {{- $servercert := .Files.Get (include "cert" (dict "path" $fromfile "file" "server.crt") ) }}
  {{- $serverkey := .Files.Get (include "cert" (dict "path" $fromfile "file" "server.key") ) }}
  
  ca.crt: {{ $cacert | b64enc }}
  server.crt: {{ $servercert | b64enc }}
  server.key: {{ $serverkey | b64enc }}
{{- else }}
{{- with .Values.control.controlApiTLS.certificates }}
  ca.crt: {{ .ca | b64enc }}
  server.crt: {{ .cert | b64enc }}
  server.key: {{ .key | b64enc }}
{{- end }}
{{- end }}
{{- end }} 
{{- end }}
{{- end }}