{{ $dataMasterKey := "" }}

{{ if eq .Values.data.master_key "" }}
{{ $dataMasterKey = (randAlpha 16) | b64enc | quote }}
{{- $secret := (lookup "v1" "Secret" $.Release.Namespace ".Values.data.name-secrets") }}
{{- if $secret }}
{{- $dataMasterKey = index $secret.data .master_key }}
{{- end }}
{{ else }}
{{ $dataMasterKey = .Values.data.master_key | b64enc | quote }}
{{ end }}

kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.data.name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
{{- if .Values.data.aws }}
{{- with .Values.data.aws }}
  aws_access_key_id: "{{ .access_key }}"
  aws_secret_access_key: "{{ .secret_key }}"
  aws_region: "{{ .region }}"
  aws_s3_bucket: "{{ .bucket }}"
{{- end }}
{{- end }}
  master_key: {{ $dataMasterKey }}
