{{ with .Values.data }}
{{ $dataMasterKey := "" }}

{{- $secret := (lookup "v1" "Secret" $.Release.Namespace .secret_name) }}
{{- if $secret }}
  {{- $dataMasterKey = index $secret.data.master_key | b64dec }}
{{- else }}
  {{ if eq .master_key "" }}
    {{ $dataMasterKey = (randAlpha 32) }}
  {{ else }}
    {{ $dataMasterKey = .dataMasterKey }}
  {{ end }}
{{ end }}

kind: Secret
apiVersion: v1
metadata:
  name: {{ .secret_name }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
stringData:
{{- if .aws }}
{{- with .aws }}
  aws_access_key_id: "{{ .access_key }}"
  aws_secret_access_key: "{{ .secret_key }}"
  aws_region: "{{ .region }}"
  aws_s3_bucket: "{{ .bucket }}"
{{- end }}
{{- end }}
  master_key: {{ $dataMasterKey }}
{{ end }}