{{ if .Values.edge.certificates.ingress }}
{{ $cert := .Values.edge.certificates.ingress}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $cert.name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
{{- if or (not .Values.global.global_certs.enabled) (.Values.edge.certificates.ingress.unique) }}
  # not global OR UNIQUE is true
  {{- if $cert.from_file.enabled }}
  # from file is TRUE
  {{- $fromfile := $cert.from_file.path }}

  {{- $cacert := .Files.Get (include "cert" (dict "path" $fromfile "file" "ca.crt") ) }}
  {{- $servercert := .Files.Get (include "cert" (dict "path" $fromfile "file" "server.crt") ) }}
  {{- $serverkey := .Files.Get (include "cert" (dict "path" $fromfile "file" "server.key") ) }}
  
  ca.crt: {{ $cacert | b64enc }}
  ca_b64: {{ $cacert | b64enc | b64enc }}
  server.crt: {{ $servercert| b64enc }}
  cert_b64: {{ $servercert| b64enc | b64enc }}
  server.key: {{ $serverkey | b64enc }}
  key_b64: {{ $serverkey | b64enc | b64enc }}

  {{- else }}
  # from file is FALSe
  ca.crt: {{ $cert.ca | b64enc }}
  ca_b64: {{ $cert.ca | b64enc | b64enc }}
  server.crt: {{ $cert.cert | b64enc }}
  cert_b64: {{ $cert.cert | b64enc | b64enc }}
  server.key: {{ $cert.key | b64enc }}
  key_b64: {{ $cert.key | b64enc | b64enc }}
  {{- end }}
{{- else }}
  # global is true and unique is FALSE
  {{- if .Values.global.global_certs.certificates.from_file.enabled }}
  # global is also from file
  {{- $fromfile := $.Values.global.global_certs.certificates.from_file.path }}

  {{- $cacert := .Files.Get (include "cert" (dict "path" $fromfile "file" "ca.crt") ) }}
  {{- $servercert := .Files.Get (include "cert" (dict "path" $fromfile "file" "server.crt") ) }}
  {{- $serverkey := .Files.Get (include "cert" (dict "path" $fromfile "file" "server.key") ) }}
  
  ca.crt: {{ $cacert | b64enc }}
  server.crt: {{ $servercert | b64enc }}
  server.key: {{ $serverkey | b64enc }}
  {{- else }}
  # global is not from file
  {{- with .Values.global.global_certs.certificates }}
  ca.crt: {{ .ca | b64enc }}
  server.crt: {{ .cert | b64enc }}
  server.key: {{ .key | b64enc }}
  {{- end }}
  {{- end }}

{{- end }}

{{- end }}