{{- if and (.Values.global.global_certs.enabled) (not .Values.edge.certificates.ingress.unique)}}
{{ if .Values.edge.certificates.ingress }}
{{ $cert := .Values.edge.certificates.ingress}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $cert.name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
{{- if .Values.global.global_certs.certificates.from_file.enabled }}
  {{- $fromfile := $.Values.global.global_certs.certificates.from_file.path }}

  {{- $cacert := .Files.Get (include "cert" (dict "path" $fromfile "file" "ca.crt") ) }}
  {{- $servercert := .Files.Get (include "cert" (dict "path" $fromfile "file" "server.crt") ) }}
  {{- $serverkey := .Files.Get (include "cert" (dict "path" $fromfile "file" "server.key") ) }}
  
  ca.crt: {{ $cacert | b64enc }}
  server.crt: {{ $servercert | b64enc }}
  server.key: {{ $serverkey | b64enc }}
{{- else }}
{{- with .Values.global.global_certs.certificates }}
  ca.crt: {{ .ca | b64enc }}
  server.crt: {{ .cert | b64enc }}
  server.key: {{ .key | b64enc }}
{{- end }}
{{- end }}



{{- end }}
{{- end }}