{{- if not .Values.global.global_certs.enabled }}
{{ if .Values.edge.certificates.egress }}
{{ $cert := .Values.edge.certificates.egress}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $cert.name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
  {{- if $cert.from_file.enabled }}
  {{- $fromfile := $cert.from_file.path }}

  {{- $cacert := .Files.Get (include "cert" (dict "path" $fromfile "file" "ca.crt") ) }}
  {{- $servercert := .Files.Get (include "cert" (dict "path" $fromfile "file" "server.crt") ) }}
  {{- $serverkey := .Files.Get (include "cert" (dict "path" $fromfile "file" "server.key") ) }}
  
  ca.crt: {{ $cacert | b64enc }}
  ca_b64: {{ $cacert | b64enc | b64enc }}
  server.crt: {{ $servercert| b64enc }}
  cert_b64: {{ $servercert| b64enc | b64enc }}
  server.key: {{ $serverkey | b64enc }}
  key_b64: {{ $serverkey | b64enc | b64enc }}

  {{- else }}
  ca.crt: {{ $cert.ca | b64enc }}
  ca_b64: {{ $cert.ca | b64enc | b64enc }}
  server.crt: {{ $cert.cert | b64enc }}
  cert_b64: {{ $cert.cert | b64enc | b64enc }}
  server.key: {{ $cert.key | b64enc }}
  key_b64: {{ $cert.key | b64enc | b64enc }}
{{- end }}
{{- end }}

{{- end }}