{{ with .Values.internalmongo.credentials }}
{{ $rootPassword := "" }}
{{ $gmdataPassword := "" }}

{{- $secret := (lookup "v1" "Secret" $.Release.Namespace .secret_name) }}
{{- if $secret }}
  {{- $rootPassword = index $secret.data.root_password | b64dec }}
{{- else }}
  {{ if eq .root_password "" }}
    {{ $rootPassword = (randAlpha 32) }}
  {{ else }}
    {{ $rootPassword = .root_password }}
  {{ end }}
{{ end }}

{{- $secret := (lookup "v1" "Secret" $.Release.Namespace .secret_name) }}
{{- if $secret }}
  {{- $gmdataPassword = index $secret.data.gmdata_password | b64dec }}
{{- else }}
  {{ if eq .gmdata_password "" }}
    {{ $gmdataPassword = (randAlpha 32) }}
  {{ else }}
    {{ $gmdataPassword = .root_password }}
  {{ end }}
{{ end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .secret_name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
stringData:
  root_username: {{ .root_username }}
  root_password: {{ $rootPassword }}
  {{ with .gmdata_username }}
  gmdata_username: {{ . }}
  {{- end }}
  gmdata_password: {{ $gmdataPassword }}
  database: {{ .database }}
{{- end }}
