{{ if .Values.internaljwt.secrets }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.internaljwt.secrets.certs.name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
# use global certs
  {{- if .Values.global.global_certs.enabled }}
# -- use file
  {{- if .Values.global.global_certs.certificates.from_file.enabled }}
  {{- $fromfile := .Values.global.global_certs.certificates.from_file.path }}
  {{- $cacert := .Files.Get (include "cert" (dict "path" $fromfile "file" "ca.crt") ) }}
  {{- $servercert := .Files.Get (include "cert" (dict "path" $fromfile "file" "server.crt") ) }}
  {{- $serverkey := .Files.Get (include "cert" (dict "path" $fromfile "file" "server.key") ) }}
  
  jwt.trust.pem: {{ $cacert | b64enc | b64enc }}
  jwt.cert.pem: {{ $servercert | b64enc | b64enc }}
  jwt.key.pem: {{ $serverkey | b64enc | b64enc }}
  server.trust.pem: {{ $cacert | b64enc | b64enc }}
  server.cert.pem: {{ $servercert | b64enc | b64enc }}
  server.key.pem: {{ $serverkey | b64enc | b64enc }}
  
  {{- else }}
# -- use values
  {{- $certs := .Values.global.global_certs.certificates }}
  {{- $cacert := $certs.ca }}
  {{- $servercert := $certs.cert }}
  {{- $serverkey := $certs.key }}

  jwt.trust.pem: {{ $cacert | b64enc | b64enc }}
  jwt.cert.pem: {{ $servercert | b64enc | b64enc }}
  jwt.key.pem: {{ $serverkey | b64enc | b64enc }}
  server.trust.pem: {{ $cacert | b64enc | b64enc }}
  server.cert.pem: {{ $servercert | b64enc | b64enc }}
  server.key.pem: {{ $serverkey | b64enc | b64enc }}

  {{- end }}

  {{- else }}
# use local certs

# -- use file
  {{- if .Values.internaljwt.secrets.certs.from_file.enabled }}
  {{- $fromfile := .Values.internaljwt.secrets.certs.from_file.path }}

  {{- $cacert := .Files.Get (include "cert" (dict "path" $fromfile "file" "ca.crt") ) }}
  {{- $servercert := .Files.Get (include "cert" (dict "path" $fromfile "file" "server.crt") ) }}
  {{- $serverkey := .Files.Get (include "cert" (dict "path" $fromfile "file" "server.key") ) }}
  
  jwt.trust.pem: {{ $cacert | b64enc | b64enc }}
  jwt.cert.pem: {{ $servercert | b64enc | b64enc }}
  jwt.key.pem: {{ $serverkey | b64enc | b64enc }}
  server.trust.pem: {{ $cacert | b64enc | b64enc }}
  server.cert.pem: {{ $servercert | b64enc | b64enc }}
  server.key.pem: {{ $serverkey | b64enc | b64enc }}

  {{- else }}
# -- use values
  {{- $certs := .Values.internaljwt.secrets.certs }}

  jwt.trust.pem: {{ $certs.jwt_trust_pem | b64enc | b64enc }}
  jwt.cert.pem: {{ $certs.jwt_cert_pem| b64enc | b64enc }}
  jwt.key.pem: {{ $certs.jwt_key_pem | b64enc | b64enc }}
  server.trust.pem: {{ $certs.server_trust_pem | b64enc | b64enc }}
  server.cert.pem: {{ $certs.server_cert_pem | b64enc | b64enc }}
  server.key.pem: {{ $certs.server_key_pem | b64enc | b64enc }}

  {{- end }}
  {{- end }}
{{- end }}