{{ if .Values.internaldata }}
{{ $internalDataMasterKey := "" }}

{{ if eq .Values.internaldata.master_key "" }}
{{ $internalDataMasterKey = (randAlpha 16) | b64enc | quote }}
{{- $secret := (lookup "v1" "Secret" $.Release.Namespace ".Values.internaldata.name-secrets") }}
{{- if $secret }}
{{- $internalDataMasterKey = index $secret.data .master_key }}
{{- end }}
{{ else }}
{{ $internalDataMasterKey = .Values.internaldata.master_key | b64enc | quote }}
{{ end }}

kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.internaldata.name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
{{- if .Values.internaldata.aws }}
{{- with .Values.internaldata.aws }}
  aws_access_key_id: "{{ .access_key }}"
  aws_secret_access_key: "{{ .secret_key }}"
  aws_region: "{{ .region }}"
  aws_s3_bucket: "{{ .bucket }}"
{{- end }}
{{- end }}
  master_key: {{ $internalDataMasterKey }}
{{- end }}
