{{ if .Values.internaldata }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.internaldata.name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
{{- if .Values.internaldata.aws }}
{{- with .Values.internaldata.aws }}
  aws_access_key_id: {{ .access_key }}
  aws_secret_access_key: {{ .secret_key }}
  aws_region: {{ .region }}
  aws_s3_bucket: {{ .bucket }}
{{- end }}
{{- end }}
  master_key: {{ .Values.internaldata.master_key }}
{{- end }}
