{{ with .Values.internalredis }}
{{ $internalRedisPassword := "" }}

{{- $secret := (lookup "v1" "Secret" $.Release.Namespace .secret_name) }}
{{- if $secret }}
  {{- $internalRedisPassword = index $secret.data.password | b64dec }}
{{- else }}
  {{ if eq .password "" }}
    {{ $internalRedisPassword = (randAlpha 32) }}
  {{ else }}
    {{ $internalRedisPassword = .password }}
  {{ end }}
{{ end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .secret_name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
stringData:
  password: {{ $internalRedisPassword }}
{{ end }}