{{ with .Values.internalmongo.credentials }}
{{ $rootPassword := "" }}
{{ $gmdataPassword := "" }}

{{ if eq .root_password "" }}
{{ $rootPassword = (randAlpha 16) }}
{{- $secret := (lookup "v1" "Secret" $.Release.Namespace .secret_name) }}
{{- if $secret }}
{{- $rootPassword = index $secret.data .root_password }}
{{- end }}
{{ else }}
{{ $rootPassword = .root_password }}
{{ end }}
{{ if eq .gmdata_password "" }}
{{ $gmdataPassword = (randAlpha 16) }}
{{- $secret := (lookup "v1" "Secret" $.Release.Namespace .secret_name) }}
{{- if $secret }}
{{- $gmdataPassword = index $secret.data .gmdata_password }}
{{- end }}
{{ else }}
{{ $gmdataPassword = .gmdata_password }}
{{ end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .secret_name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
stringData:
  root_username: {{ .root_username }}
  root_password: {{ $rootPassword }}
  {{ with .gmdata_username }}
  gmdata_username: {{ . }}
  {{- end }}
  gmdata_password: {{ $gmdataPassword }}
  database: {{ .database }}
{{- end }}
