{{- $root := . -}}
{{ if .Values.internaljwt.secrets }}
{{- $secrets := .Values.internaljwt.secrets.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secrets.name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:

# if from file
{{- if $secrets.from_file.enabled }}
  {{- $fromfile := $secrets.from_file.path }}
  {{- range $key , $value := $secrets }}
  {{- if and (ne $key "name") (ne $key "from_file") (ne $key "jwt.api_key") }}
  {{- $value := $root.Files.Get (include "cert" (dict "path" $fromfile "file" $key) ) }} 
  {{ base $key }}: {{ $value | b64enc | b64enc}}
  {{- else if and (eq $key "jwt.api_key") }}
  {{ base $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}

{{- else }}
# else use values file
  {{- range $key, $value := $secrets }}
  {{- if and (ne $key "name") (ne $key "from_file") }}
  {{- if  and (eq $key "jwt.api_key") }}
  {{ base $key }}: {{ $value | b64enc }}
  {{- else }}
  {{ base $key }}: {{ $value | b64enc | b64enc }}
  {{- end }}
  {{- end }}
  {{- end }}


{{- end }}
# end


{{- end }}