{{ $customer_name := regexReplaceAll "\\W+" .Values.global.release.customer  "-" }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: greymatter-mesh-identity-{{ print $customer_name }}
  namespace: {{ $.Release.Namespace }}
data:
  customer: {{ print $customer_name }}
  rand_identifier: {{ randAlphaNum 6 | lower  }}
