{{ $external_redis_config := $.Values.global.external_redis }}
{{ $local_redis_config := $.Values.mesh_redis }}

# if not external disabled then it is enabled --- so this means we are using an external redis
{{ $redis_config := "" }}
{{ if not $.Values.global.external_redis.disabled }}
{{ $redis_config = $external_redis_config }}
{{ else }}
{{ $redis_config = $local_redis_config }}
{{ end }}


{{ with $redis_config }}
{{ $redisPassword := "" }}

{{- $secret := (lookup "v1" "Secret" $.Release.Namespace .secret_name) }}
{{- if $secret }}
  {{- $redisPassword = index $secret.data.password | b64dec }}
{{- else }}
  {{ if eq .password "" }}
    {{ $redisPassword = (randAlpha 32) }}
  {{ else }}
    {{ $redisPassword = .password }}
  {{ end }}
{{ end }}


apiVersion: v1
kind: Secret
metadata:
  name: {{ .secret_name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
stringData:
  password: {{ $redisPassword }}
{{ end }}