apiVersion: v1
kind: ConfigMap
metadata:
  name: greymatter-mesh-identity-{{.Values.global.release.customer}}
  namespace: {{ $.Release.Namespace }}
data:
  customer: {{.Values.global.release.customer }}
  rand_identifier: {{ randAlphaNum 6 | lower  }}
