{{ with .Values.postgres.credentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secret_name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
stringData:
  username: {{ .username }}
  password: {{ .password }}
  database: {{ .database }}
{{- end }}