{{ with .Values.postgres.credentials }}
{{ $postgresPassword := "" }}

{{- $secret := (lookup "v1" "Secret" $.Release.Namespace .secret_name) }}
{{- if $secret }}
  {{- $postgresPassword = index $secret.data.password | b64dec }}
{{- else }}
  {{ if eq .password "" }}
    {{ $postgresPassword = (randAlpha 32) }}
  {{ else }}
    {{ $postgresPassword = .password }}
  {{ end }}
{{ end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .secret_name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
stringData:
  username: {{ .username }}
  password: {{ $postgresPassword }}
  database: {{ .database }}
{{- end }}