{{ with .Values.redis }}
{{ $redisPassword := "" }}

{{ if eq .password "" }}
{{ $redisPassword = (randAlpha 16) | b64enc | quote }}
{{- $secret := (lookup "v1" "Secret" $.Release.Namespace .secret_name) }}
{{- if $secret }}
{{- $redisPassword = index $secret.data .password }}
{{- end }}
{{ else }}
{{ $redisPassword = .password | b64enc | quote }}
{{ end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .secret_name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
stringData:
  password: {{ $redisPassword }}
{{ end }}