{{ if .Values.sidecar.certificates }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sidecar.certificates.name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
{{- if .Values.sidecar.certificates.from_file.enabled }}
  {{- $fromfile := $.Values.sidecar.certificates.from_file.path }}

  {{- $cacert := .Files.Get (include "cert" (dict "path" $fromfile "file" "ca.crt") ) }}
  {{- $servercert := .Files.Get (include "cert" (dict "path" $fromfile "file" "server.crt") ) }}
  {{- $serverkey := .Files.Get (include "cert" (dict "path" $fromfile "file" "server.key") ) }}

  ca.crt: {{ $cacert | b64enc }}
  ca_b64: {{ $cacert | b64enc | b64enc }}
  server.crt: {{ $servercert | b64enc }}
  cert_b64: {{ $servercert | b64enc | b64enc}}
  server.key: {{ $serverkey | b64enc }}
  key_b64: {{ $serverkey | b64enc | b64enc}}
{{- else }}
{{- with .Values.sidecar.certificates }}
  ca.crt: {{ .ca | b64enc }}
  ca_b64: {{ .ca | b64enc | b64enc }}
  server.crt: {{ .cert | b64enc }}
  cert_b64: {{ .cert | b64enc | b64enc }}
  server.key: {{ .key | b64enc }}
  key_b64: {{ .key | b64enc | b64enc }}
{{- end }}
{{- end }}
{{- end }}