{{ if not .Values.global.global_certs.enabled }}
{{- if .Values.slo.ssl.enabled }}
{{ if .Values.slo.ssl.certificates }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.slo.ssl.name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
{{- if .Values.slo.ssl.certificates.from_file.enabled }}
  {{- $fromfile := $.Values.slo.ssl.certificates.from_file.path }}
  {{ .caName }}: {{ .Files.Get (include "cert" (dict "path" $fromfile "file" "ca.crt") ) | b64enc }}
  {{ .certName }}: {{ .Files.Get (include "cert" (dict "path" $fromfile "file" "server.crt") ) | b64enc }}
  {{ .keyName }}: {{ .Files.Get (include "cert" (dict "path" $fromfile "file" "server.key") ) | b64enc }}
{{- else }}
{{- with .Values.slo.ssl.certificates }}
  {{ .caName }}: {{ .ca | b64enc }}
  {{ .certName }}: {{ .cert | b64enc }}
  {{ .keyName }}: {{ .key | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}