{{- if .Values.data.deploy.standalone }}
{{- if .Values.data.deploy.secrets }}
{{- $secrets := .Values.data.deploy.secrets.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secrets.name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
  {{- range $key, $value := $secrets }}
  {{- if and (ne $key "name") }}
  {{- if  and (eq $key "jwt.api_key") }}
  {{ base $key }}: {{ $value | b64enc }}
  {{- else }}
  {{ base $key }}: {{ $value | b64enc | b64enc }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}