apiVersion: v2
appVersion: 1.1.0
description: A Helm chart to deploy Grey Matter Catalog
name: catalog
version: 3.0.12
home: https://greymatter.io
icon: https://s3.amazonaws.com/decipher-public/grey-matter/branding/grey-matter-mark-rgb.png
maintainers:
  - name: greymatter-io
    email: engineering@greymatter.io
keywords:
  - Grey Matter
  - service mesh
