apiVersion: v2
appVersion: 1.0.3
description: A Helm chart to deploy Grey Matter Catalog
name: catalog
version: 2.2.2
icon: https://s3.amazonaws.com/decipher-public/grey-matter/branding/grey-matter-mark-rgb.png
maintainers:
  - name: Decipher Technology Studios Engineering
    email: engineering@deciphernow.com
    website: deciphernow.com
keywords:
  - Grey Matter
  - service mesh
