kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    {{ .Values.global.control.cluster_label }}: {{ .Values.redis.name }}
  name: {{ .Values.redis.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.redis.replica_count  }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{ .Values.global.control.cluster_label }}: {{ .Values.redis.name }}
      deployment: {{ .Values.redis.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{ .Values.global.control.cluster_label }}: {{ .Values.redis.name }}
        deployment: {{ .Values.redis.name }}
    spec:
      containers:
        - name: redis
          {{- if and .Values.global.environment (eq .Values.global.environment "openshift") }}
          image: {{ .Values.redis.openshift.image }}
          {{- else }}
          image: {{ .Values.redis.k8s.image }}
          command:
            - 'redis-server'
          args:
            - '--requirepass'
            - "$(REDIS_PASSWORD)"
          {{- end }}
          env:
          {{- include "jwt.envvars" (dict "envvar" .Values.redis.envvars "top" $) | indent 12 }}
          imagePullPolicy: {{ .Values.redis.image_pull_policy }}
        {{- if .Values.redis.resources }}
          resources:
{{ toYaml .Values.redis.resources | indent 12 }}
        {{- end }}
      {{- if .Values.redis.private_image }}
      imagePullSecrets:
      - name: {{ .Values.global.image_pull_secret }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
#  test: false
#  triggers:
#    - type: ConfigChange
