# Default values for gm-control-api.
global:
  environment: kubernetes
  domain:
  route_url_name:
  remove_namespace_from_url: ''
  exhibitor:
    replicas: 1
  spire:
    enabled: true
    trustDomain: deciphernow.com
  waiter:
    image: deciphernow/k8s-waiter:latest

spire:
  clusterName: k8s
  server:
    name: spire-server

    # This spire Docker registry requires an explicit version, it doesn't have a tag latest
    image: gcr.io/spiffe-io/spire-server:0.8.1 #0.7.3
    # Registration API UDS location
    registrationAPIPath: /tmp/spire/registration/registration.sock
    registrationAPIDir: /tmp/spire/registration
    # Spire server config file location
    configFilePath: /run/spire/config/server.conf
    configFileDir: /run/spire/config
    # The spire server ServiceAccount is used to validate Kubernetes tokens using the Token Review API
    serviceAccount:
      create: true
      name: spire-server-sa
  agent:
    image: gcr.io/spiffe-io/spire-agent:0.8.1
    # The spire agent ServiceAccount is used by the spire agent to read all the properties of pods to create Kubernetes selectors used for attesting the identity of workloads
    serviceAccount:
      create: true
      name: spire-agent-sa

  certs:
    # This certificate must match the trust domain specified above
    bootstrap:
      # TODO: add support for joining upstream CA
      # ca: |-
      #   -----BEGIN CERTIFICATE-----
      #   ...
      #   -----END CERTIFICATE-----
      crt: |-
        -----BEGIN CERTIFICATE-----
        ...
        -----END CERTIFICATE-----
      key: |-
        -----BEGIN RSA PRIVATE KEY-----
        ...
        -----END RSA PRIVATE KEY-----