# These are the expected environment variables
#
# The Nexus information is so that the build can push the packaged charts to the Decipher Helm repo
# NEXUS_URL
# NEXUS_PASSWORD
# NEXUS_USER
#
version: 2

jobs:
  build-development:
    machine: true
    steps:
      - checkout
      - run:
          name: Set Environment Variable
          command: |
            echo "export NEXUS_URL=https://nexus.greymatter.io/repository/helm/development/" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Package and Publish Catalog
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/sense/catalog
      - run:
          name: Package and Publish Control
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/fabric/control
      - run:
          name: Package and Publish Data
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/data/gm-data
      - run:
          name: Package and Publish GM Control API
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/fabric/control-api
      - run:
          name: Package and Publish Dashboard
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/sense/dashboard
      - run:
          name: Package and Publish JWT
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/fabric/jwt
      - run:
          name: Package and Publish JWT Gov
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/fabric/jwt-gov
      - run:
          name: Package and Publish Edge
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/edge
      - run:
          name: Package and Publish SLO
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/sense/slo
      - run:
          name: Package and Publish Spire Server
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/spire/server
      - run:
          name: Package and Publish Spire Agent
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/spire/agent
      - run:
          name: Package and Publish Secrets
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/secrets
  package-and-publish-greymatter-development:
    machine: true
    steps:
      - checkout
      - run:
          name: Set Environment Variable
          command: |
            echo "export NEXUS_URL=https://nexus.greymatter.io/repository/helm/development/" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Change Grey Matter (fabric, sense, data, spire, secrets) Requirements from local to helm development
          command: |
            sed -i.bak -e "s|file:.*|$NEXUS_URL|" $(pwd)/fabric/Chart.yaml
            sed -i.bak -e "s|file:.*|$NEXUS_URL|" $(pwd)/sense/Chart.yaml
            sed -i.bak -e "s|file:.*|$NEXUS_URL|" $(pwd)/data/Chart.yaml
            sed -i.bak -e "s|file:.*|$NEXUS_URL|" $(pwd)/spire/Chart.yaml
            sed -i.bak -e "s|file:.*|$NEXUS_URL|" $(pwd)/secrets/Chart.yaml
      - run:
          name: Print directory listing
          command: |
            ls -al $(pwd)
      - run:
          name: Package and Publish Fabric
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/fabric
      - run:
          name: Package and Publish Fabric-gov
          command: |
            cp $(pwd)/fabric/Chart.yaml $(pwd)/fabric/Chart.yaml.orig
            echo "$(awk 'NR==1,/name: jwt/{sub(/name: jwt/, "name: jwt-gov")} 1' fabric/Chart.yaml)" > fabric/Chart.yaml
            sed -i.bak-gov -e "s|name: fabric|name: fabric-gov|" -e "s|Grey Matter Fabric|Grey Matter Fabric-gov|" $(pwd)/fabric/Chart.yaml
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/fabric
            mv $(pwd)/fabric/Chart.yaml.orig $(pwd)/fabric/Chart.yaml
      - run:
          name: Package and Publish Sense
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/sense
      - run:
          name: Package and Publish Data
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/data
      - run:
          name: Package and Publish Edge
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/edge
      - run:
          name: Package and Publish Spire
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/spire
      - run:
          name: Package and Publish Secrets
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/secrets
      - run:
          name: Revert SED
          command: |
            mv $(pwd)/fabric/Chart.yaml.bak $(pwd)/fabric/Chart.yaml
            mv $(pwd)/sense/Chart.yaml.bak $(pwd)/sense/Chart.yaml
            mv $(pwd)/data/Chart.yaml.bak $(pwd)/data/Chart.yaml
            mv $(pwd)/spire/Chart.yaml.bak $(pwd)/spire/Chart.yaml
            mv $(pwd)/secrets/Chart.yaml.bak $(pwd)/secrets/Chart.yaml
  package-and-publish-core-release:
    machine: true
    steps:
      - checkout
      - run:
          name: Set Environment Variable
          command: |
            echo "export NEXUS_URL=https://nexus.greymatter.io/repository/helm/release/" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Package and Publish Catalog
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/sense/catalog
      - run:
          name: Package and Publish Control
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/fabric/control
      - run:
          name: Package and Publish Data
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/data/gm-data
      - run:
          name: Package and Publish GM Control API
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/fabric/control-api
      - run:
          name: Package and Publish Dashboard
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/sense/dashboard
      - run:
          name: Package and Publish JWT
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/fabric/jwt
      - run:
          name: Package and Publish JWT Gov
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/fabric/jwt-gov
      - run:
          name: Package and Publish Edge
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/edge
      - run:
          name: Package and Publish SLO
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/sense/slo
      - run:
          name: Package and Publish Spire Server
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/spire/server
      - run:
          name: Package and Publish Spire Agent
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/spire/agent
      - run:
          name: Package and Publish Secrets
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/secrets
  package-and-publish-greymatter-release:
    machine: true
    steps:
      - checkout
      - run:
          name: Set Environment Variable
          command: |
            echo "export NEXUS_URL=https://nexus.greymatter.io/repository/helm/release/" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Change Grey Matter (fabric, sense, data, spire) Requirements from local to helm release
          command: |
            sed -i.bak -e "s|file:.*|$NEXUS_URL|" $(pwd)/fabric/Chart.yaml
            sed -i.bak -e "s|file:.*|$NEXUS_URL|" $(pwd)/sense/Chart.yaml
            sed -i.bak -e "s|file:.*|$NEXUS_URL|" $(pwd)/data/Chart.yaml
            sed -i.bak -e "s|file:.*|$NEXUS_URL|" $(pwd)/spire/Chart.yaml
            sed -i.bak -e "s|file:.*|$NEXUS_URL|" $(pwd)/secrets/Chart.yaml
      - run:
          name: Package and Publish Fabric
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/fabric
      - run:
          name: Package and Publish Fabric-gov
          command: |
            cp $(pwd)/fabric/Chart.yaml $(pwd)/fabric/Chart.yaml.orig
            echo "$(awk 'NR==1,/name: jwt/{sub(/name: jwt/, "name: jwt-gov")} 1' fabric/Chart.yaml)" > fabric/Chart.yaml
            sed -i.bak-gov -e "s|name: fabric|name: fabric-gov|" -e "s|Grey Matter Fabric|Grey Matter Fabric-gov|" $(pwd)/fabric/Chart.yaml
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/fabric
            mv $(pwd)/fabric/Chart.yaml.orig $(pwd)/fabric/Chart.yaml
      - run:
          name: Package and Publish Sense
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/sense
      - run:
          name: Package and Publish Data
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/data
      - run:
          name: Package and Publish Edge
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/edge
      - run:
          name: Package and Publish Spire
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/spire
      - run:
          name: Package and Publish Secrets
          command: |
            docker run --rm -e INPUT_NEXUS_URL=$NEXUS_URL -e INPUT_NEXUS_USER=$NEXUS_USER -e INPUT_NEXUS_PASS=$NEXUS_PASSWORD -v $(pwd):/helm deciphernow/helm-packager:v3.1.1 /helm/secrets
workflows:
  version: 2
  build-and-publish:
    jobs:
      - build-development:
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore: /release-.*/
      - package-and-publish-greymatter-development:
          requires:
            - build-development
      - package-and-publish-core-release:
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore: /release-2.3/
              only: /release-.*/
      - package-and-publish-greymatter-release:
          requires:
            - package-and-publish-core-release
