global:
  environment: kubernetes
  domain:
  route_url_name:
  remove_namespace_from_url: false
  zone: zone-default-zone
  dashboard:
    version: 2.5.0
  data:
    version: 0.2.3
  documentation:
    version: 3.0.0
  edge:
    version: 0.8.1
  exhibitor:
    replicas: 1
    version:
  jwt:
    version: 0.2.0
  slo:
    version: 0.4.0
  xds:
    cluster: greymatter
    port: 18000
    version: 0.2.6
  waiter:
    serviceAccount:
      Name: waiter
  control:
    name: control
    port: 50000

catalog:
  name: catalog
  version: 1.0.1
  image: docker.production.deciphernow.com/deciphernow/gm-catalog:{{ $.Values.global.catalog.version }}
  source: control
  debug: 'true'
  imagePullPolicy: Always
  resources:
    limits:
      cpu: 200m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi

  port: 9080

  init:
    image: 'docker.production.deciphernow.com/deciphernow/gm-proxy:{{ tpl $.Values.sidecar.version $ }}'
    imagePullPolicy: Always
    envvars:
      debug:
        type: 'value'
        value: 'false'
      catalog_api_host:
        type: 'value'
        value: '{{ .Values.catalog.name }}:{{ .Values.catalog.port }}'

sidecar:
  version: '{{- $.Values.global.catalog.sidecar.version | default $.Values.global.sidecar.version }}'
  image: 'docker.production.deciphernow.com/deciphernow/gm-proxy:{{ tpl $.Values.sidecar.version $ }}'
  imagePullPolicy: Always
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  envvars:
    xds_cluster:
      type: value
      value: 'catalog'
    kafka_topic:
      type: value
      value: 'gm-catalog'

  # Set this to true if you are attempting to deploy Catalog by itself.
  # Ideally, catalog is deployed as a dependency to Grey Matter, which creates the
  # sidecar secret, but if individual testing is being done, the sidecar secret will
  # need to be created.
  create_sidecar_secret: false
  certificates:
    name: sidecar
    ca: |-
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    cert: |-
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    key: |-
      -----BEGIN RSA PRIVATE KEY-----
      ...
      -----END RSA PRIVATE KEY-----
