{{- if or (.Values.sidecar.create_sidecar_secret) (.Values.global.mesh_tls.use_provided_certs) }}
{{- if .Values.sidecar.certificates }}
{{- with .Values.sidecar.certificates }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-certs
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
  ca.crt: {{ .ca | b64enc }}
  ca_b64: {{ .ca | b64enc | b64enc }}
  server.crt: {{ .cert | b64enc }}
  server_b64: {{ .cert | b64enc | b64enc }}
  server.key: {{ .key | b64enc }}
  key_b64: {{ .key | b64enc | b64enc }}
{{- end }}
{{- end }}
{{- end }}
