kind: ConfigMap
apiVersion: v1
metadata:
  name: postgres-slo-overrides
  namespace: {{ .Release.Namespace }}
data:
  postgresql.conf: |-
    # These override configs in OpenShift's postgres container located at /var/lib/pgsql/data/userdata/postgresql.conf
    ssl = on
    hba_file = '{{ .Values.postgres.confMountPoint }}/pg_hba.conf'
    ssl_cert_file = '{{ .Values.postgres.ssl.mountPoint }}/{{ .Values.postgres.ssl.certificates.certName }}'
    ssl_key_file = '{{ .Values.postgres.ssl.mountPoint }}/{{ .Values.postgres.ssl.certificates.keyName }}'
    ssl_ca_file = '{{ .Values.postgres.ssl.mountPoint }}/{{ .Values.postgres.ssl.certificates.caName }}'