kind: Service
apiVersion: v1
metadata:
  name: postgres-slo
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres-slo
spec:
  ports:
  - name: postgres
    port: 5432
  selector:
    app: postgres-slo
  type: ClusterIP
