{{- if not .Values.postgres.rds.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-slo
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "8Gi"
{{- end }}
