{{- if .Values.slo.ssl.enabled }}
{{ if .Values.slo.ssl.certificates }}
{{- with .Values.slo.ssl.certificates }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.slo.ssl.name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
  ca.crt: {{ .ca | b64enc }}
  server.crt: {{ .cert | b64enc }}
  server.key: {{ .key | b64enc }}
{{- end }}
{{- end }}
{{- end }}