kind: Deployment
apiVersion: apps/v1
metadata:
  name: slo
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: slo
      deployment: slo
  replicas: 1
  template:
    metadata:
      labels:
        app: slo
        deployment: slo
    spec:
      {{- if and .Values.global.environment (ne .Values.global.environment "openshift") }}
      securityContext:
        runAsUser: 2000
        runAsGroup: 0
        fsGroup: 2000
      {{- end }}
      serviceAccountName: {{ .Values.global.waiter.serviceAccount.name }}
      initContainers:
        - name: ensure-postgres
          image: {{ .Values.global.waiter.image }}
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: SERVICE
              value: postgres-slo
            - name: POST_DELAY
              value: "3"
      containers:
      - name: slo
        image: {{ .Values.slo.image | quote }}
        imagePullPolicy: {{ .Values.slo.imagePullPolicy }}
        {{- if .Values.slo.resources }}
        resources:
{{ toYaml .Values.slo.resources | indent 10 }}
        {{- end }}
        env:
        - name: POSTGRESQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgres.credentials.secret_name }}
              key: username
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgres.credentials.secret_name }}
              key: password
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgres.credentials.secret_name }}
              key: database 
        - name: DATABASE_URI
          value: postgres://$(POSTGRESQL_USERNAME):$(POSTGRESQL_PASSWORD)@postgres-slo.{{ .Release.Namespace }}.svc.cluster.local:5432/$(POSTGRESQL_DATABASE)
        - name: SERVICE_PORT
          value: "1337"
        {{- if .Values.postgres.ssl.enabled  }}
        - name: SSL_ENABLED
          value: {{ .Values.postgres.ssl.enabled | quote }}
        - name: SSL_SERVER_CA
          value: {{ .Values.postgres.ssl.mountPoint}}/ca.pem
        - name: SSL_SERVER_CERT
          value: {{ .Values.postgres.ssl.mountPoint}}/postgres.crt
        - name: SSL_SERVER_KEY
          value: {{ .Values.postgres.ssl.mountPoint}}/postgres.key
        volumeMounts:
        - name: postgres-certs
          mountPath: {{ .Values.postgres.ssl.mountPoint | quote }}
        {{- end }}
      - name: sidecar
        image: {{ tpl .Values.sidecar.image $ | quote }}
        imagePullPolicy: {{ .Values.sidecar.imagePullPolicy }}
        {{- if .Values.sidecar.resources }}
        resources:
{{ toYaml .Values.sidecar.resources | indent 10 }}
        {{- end }}
        ports:
        - name: proxy
          containerPort: 8080
        - name: metrics
          containerPort: 8081
        env:
        {{- include "greymatter.envvars" . | indent 8 }}
        {{- if .Values.global.spire.enabled }}
        volumeMounts:
        {{- include "sidecar_volume_mounts" . | indent 8 }}
        {{- else if and (not .Values.global.spire.enabled) (.Values.global.mesh_tls.use_provided_certs) }}
        volumeMounts:
        {{- include "sidecar_volume_certs_mount" . | indent 8 }}
        {{- end }}
      {{- if .Values.global.consul.enabled }}
      {{- $data := dict "Values" .Values "ServiceName" "slo" }}
      {{- include "consul.agent" $data | nindent 6 }}
      {{- end }}
      imagePullSecrets:
        - name: docker.secret
      volumes:
      {{- if .Values.global.spire.enabled }}
      {{- include "sidecar_volumes" . | indent 6 }}
      {{- include "sidecar_certs_volumes" . | indent 6 }}
      {{- else if and (not .Values.global.spire.enabled) (.Values.global.mesh_tls.use_provided_certs) }}
      {{- include "sidecar_certs_volumes" . | indent 6 }}
      {{- end }}
      {{- if .Values.postgres.ssl.enabled }}
      - name: postgres-certs
        secret:
          secretName: {{ .Values.postgres.ssl.name }}
          defaultMode: 0600
      {{- end }}
      {{- if .Values.global.consul.enabled }}
      - name: data-consul
        emptyDir: {}
      - name: config-consul
        emptyDir: {}
      {{- end }}
