kind: Deployment
apiVersion: extensions/v1beta1
metadata:
    name: jwt-security
    namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.global.exhibitor.replicas | default 1 }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jwt-security
      deployment: jwt-security
  template:
    metadata:
      labels:
        app: jwt-security
        deployment: jwt-security
    spec:
      containers:
      - name: jwt-security
        image: {{ .Values.jwt.image | quote }}
        imagePullPolicy: {{ .Values.jwt.imagePullPolicy }}
        {{- if .Values.jwt.resources }}
        resources:
{{ toYaml .Values.jwt.resources | indent 10 }}
        {{- end }}
        {{- if .Values.jwt.command }}
        command:
{{ toYaml .Values.jwt.command | indent 8 }}
        args:
{{ toYaml .Values.jwt.args | indent 8 }}
        {{- end }}
        

        env:
      {{- range $envvar := .Values.jwt.envvars }}
      {{- $envName := $envvar.name | upper | replace "." "_" | replace "-" "_" }}
        {{- if eq $envvar.type "secret" }}
        - name: {{ $envName }}
          valueFrom:
            secretKeyRef:
              name: {{ $envvar.secret }}
              key: {{ $envvar.key }}
        {{- else if eq $envvar.type "value" }}
        - name: {{ $envName }}
          value: {{ $envvar.value | quote }}
        {{- end }}
      {{- end  }}   
        - name: REDIS_HOST
          value: redis.{{ .Release.Namespace }}.svc.cluster.local
        - name:  REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: {{ .Values.jwt.redis_db | quote }}
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.redis.secret_name }}
              key: password
        ports:
        - containerPort: 3000
          name: internal
          protocol: TCP
        volumeMounts:
        - name: jwt-users
          mountPath: {{ .Values.jwt.users_mount_point }}
      - name: sidecar
        env:
        {{- include "greymatter.envvars" . | indent 8 }}
        - name: XDS_CLUSTER
          value: {{ .Values.global.xds.cluster  | quote }}
        - name: XDS_HOST
          value: "xds.{{ .Release.Namespace }}.svc.cluster.local"
        - name: XDS_PORT
          value: {{ .Values.global.xds.port | quote }}
        - name: ZK_ADDRS
          value: {{ template "greymatter.exhibitor.address" . }}
        - name: ZK_ANNOUNCE_PATH
          value: "/services/jwt-security/{{ .Values.jwt.version }}"
        image: {{ tpl $.Values.sidecar.image $ }}
        imagePullPolicy: {{ .Values.sidecar.imagePullPolicy }}
        {{- if .Values.sidecar.resources }}
        resources:
{{ toYaml .Values.sidecar.resources | indent 10 }}
        {{- end }}
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
          name: metrics
          protocol: TCP
        volumeMounts:
        - name: sidecar
          mountPath: /etc/proxy/tls/sidecar
      imagePullSecrets:
        - name: docker.secret
      volumes:
        - name: sidecar
          secret:
            secretName: sidecar
        - name: jwt-security
          secret:
            secretName: jwt-security
        - name: jwt-users
          configMap:
            name: jwt-users
