kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: {{ .Values.redis.name | default "redis" }}
  name: {{ .Values.redis.name | default "redis" }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.redis.replica_count  }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.redis.name }}
      deployment: {{ .Values.redis.name }}
  strategy:
#    activeDeadlineSeconds: 21600
#    resources: {}
    rollingUpdate:
#      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
#      timeoutSeconds: 600
#      updatePeriodSeconds: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.redis.name }}
        deployment: {{ .Values.redis.name }}
    spec:
      containers:
        - name: redis
          {{- if and .Values.global.environment (eq .Values.global.environment "openshift") }}
          image: {{ .Values.redis.openshift.image }}
          {{- else }}
          image: {{ .Values.redis.k8s.image }}
          command:
            - 'redis-server'
          args:
            - '--requirepass'
            - "$(REDIS_PASSWORD)"
          {{- end }}
          env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.redis.secret_name }}
                key: password
          imagePullPolicy: {{ .Values.redis.imagePullPolicy }}
        {{- if .Values.redis.resources }}
          resources:
{{ toYaml .Values.redis.resources | indent 12 }}
        {{- end }}
      {{- if .Values.redis.private_image }}
      imagePullSecrets:
      - name: docker.secret
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
#  test: false
#  triggers:
#    - type: ConfigChange
