# Default values for gm-control
global:
  environment: kubernetes
  domain:
  route_url_name:
  remove_namespace_from_url: ''
  exhibitor:
    replicas: 1
  control:
    version: 1.0.2
    additionalNamespacesToControl:
  waiter:
    image: deciphernow/k8s-waiter:latest

control:
  name: 'control'
  port: 50000
  # This represents the namespaces that the control server will be aware of and able to monitor.  It should be a comma delimited list.
  # The namespace used for the deployment will be include by default For example, "projecta,projectb"
  displayName: 'Control'
  replicas: 1
  image: 'docker.production.deciphernow.com/deciphernow/gm-control:{{ $.Values.global.control.version }}'
  imagePullPolicy: IfNotPresent
  serviceAccount:
    create: true
    name: control-sa
  envvars:
    gm_control_console_level:
      type: 'value'
      value: 'info'
    gm_control_api_key:
      type: 'value'
      value: 'xxx'
    gm_control_api_zone_name:
      type: 'value'
      value: 'default-zone'
    gm_control_api_ssl:
      type: 'value'
      value: 'false'
    gm_control_api_host:
      type: 'value'
      value: 'gm-control-api:5555'
    gm_control_cmd:
      type: 'value'
      value: 'kubernetes'
    # gm_control_file_format:
    #   type: 'value'
    #   value: 'yaml'
    # gm_control_file_filename:
    #   type: 'value'
    #   value: '/app/routes.yaml'
    gm_control_xds_resolve_dns:
      type: 'value'
      value: 'true'
    gm_control_xds_ads_enabled:
      type: 'value'
      value: 'true'
    gm_control_kubernetes_cluster_label:
      type: 'value'
      value: 'app'
    gm_control_kubernetes_port_name:
      type: 'value'
      value: 'proxy'
    gm_control_kubernetes_namespaces:
      type: 'value'
      value: '{{ include "control.namespaces" . }}'
    # gm_control_diff_dry_run:
    #   type: 'value'
    #   value: 'true'
  resources:
    {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
