# Grey Matter Control Defaults

global:
  # Used as imagePullSecrets value for each subchart
  image_pull_secret: docker.secret
  # Deployment environment, one of "eks", "kuberenetes", or "openshift"
  environment: openshift              
  # Used to configure control and control-api environment variables
  zone: zone-default-zone             
  # Whether to use consul for service discovery
  consul:                             
    enabled: false
    host: ''
    port: 8500
    edge_port: 10808
  control:
    # Port for Grey Matter Control. Used in sidecar envvars
    port: 50000
    # The label Control uses to find pods to include in the mesh
    cluster_label: greymatter.io/control
    # Comma delimited string of namespaces for control to monitor. Also used by prometheus. 
    additional_namespaces:
  # Configures the init container used to wait on various deployments to be ready
  waiter:                             
    image: deciphernow/k8s-waiter:latest
    service_account: 
      create: true
      name: waiter-sa

control:
  # Name used for the deployment and service resources
  name: 'control'
  # Display name used for NOTES.txt
  display_name: 'Control'
  # Number of replicas for the deployment
  replicas: 1
  # Version of control
  version: 1.5.0-dev
  image: 'docker.greymatter.io/development/gm-control:{{ $.Values.control.version }}'
  # When to pull images, used in the deployment
  image_pull_policy: IfNotPresent
  # Secret used to talk to control-api
  secret:
    enabled: true
    secret_name: control-certs
    mount_point: /service-certs
    insecure: true
    secret_keys:
      cert: server.crt
      key: server.key
  # The name of the service account with access to pods and endpoints. Can be created if it doesn't exist.
  service_account:
    create: true
    name: control-sa
  envvars:
    gm_control_api_insecure:
      type: 'value'
      value: "{{ .Values.control.secret.insecure }}"
    gm_control_api_ssl:
      type: 'value'
      value: "{{ .Values.control.secret.enabled }}"
    gm_control_api_sslcert:
      type: 'value'
      value: "{{ .Values.control.secret.mount_point }}/{{ .Values.control.secret.secret_keys.cert }}"
    gm_control_api_sslkey:
      type: 'value'
      value: "{{ .Values.control.secret.mount_point }}/{{ .Values.control.secret.secret_keys.key }}"
    gm_control_console_level:
      type: 'value'
      value: 'info'
    gm_control_api_key:
      type: 'value'
      value: 'xxx'
    gm_control_api_zone_name:
      type: 'value'
      value: '{{ .Values.global.zone }}'
    gm_control_api_host:
      type: 'value'
      value: 'control-api:5555'
    gm_control_cmd:
      type: 'value'
      value: 'kubernetes'
    gm_control_xds_resolve_dns:
      type: 'value'
      value: 'true'
    gm_control_xds_ads_enabled:
      type: 'value'
      value: 'true'
    gm_control_kubernetes_cluster_label:
      type: 'value'
      value: "{{ .Values.global.control.cluster_label }}"
    gm_control_kubernetes_port_name:
      type: 'value'
      value: 'proxy'
    gm_control_kubernetes_namespaces:
      type: 'value'
      value: '{{ include "control.namespaces" . }}'
    # The following values are not applied. Change the 'type' to 'value' to use these variables.
    gm_control_diff_dry_run:
      type: 'null'
      value: 'true'
    gm_control_file_format:
      type: 'null'
      value: 'yaml'
    gm_control_file_filename:
      type: 'null'
      value: '/app/routes.yaml'
  resources:  {}
