{{/*
Defines the edge ingress.  can be reused by passing in annotations, rules, and apiVersion
*/}}
{{- define "edge-ingress" }}
{{- $ingress := index . "ingress" }}
{{- $root := index . "root" }}
{{- $name := index . "name" }}
apiVersion: {{ $ingress.apiVersion }}
kind: Ingress
metadata:
  name: {{ $name }}
  namespace: {{ $root.Release.Namespace }}
  annotations:
{{ toYaml $ingress.annotations | indent 4 }}
spec:
  rules:
{{ tpl (toYaml $ingress.rules) $root | indent 4 }}
{{- end }}


{{- if and .Values.global.environment (eq .Values.global.environment "openshift") }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.edge.name }}
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ include "greymatter.domain" . }}
  port:
    targetPort: proxy
  tls:
    termination: passthrough
  to:
    kind: Service
    name: {{ .Values.edge.name }}
    weight: 100
  wildcardPolicy: None
{{ include "openshift.route.fix" $ }}

{{- else }}

# Create nginx or voyager ingress using template
{{- $root := $ }}
{{- $name := .Values.edge.name -}}
{{- if .Values.edge.ingress.use_voyager }}
{{- $ingress := .Values.edge.ingress.voyager }}
{{- include "edge-ingress" (dict "ingress" $ingress "root" $root "name" $name) }}

{{- else }}
{{- $ingress := .Values.edge.ingress.nginx}}

{{- include "edge-ingress" (dict "ingress" $ingress "root" $root "name" $name) }}

{{- end }}

{{- end }}