kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.edge.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ .Values.global.control.cluster_label }}: {{ .Values.edge.name }}
spec:
  ports:
    - name: proxy
      port: 10808
    - name: metrics
      port: 8081
  selector:
    {{ .Values.global.control.cluster_label }}: {{ .Values.edge.name }}
  sessionAffinity: None
  type: {{ .Values.edge.ingress.type }}