{{- if and .Values.global.environment (eq .Values.global.environment "openshift") }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: edge
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ include "greymatter.domain" . }}
  port: 
    targetPort: proxy
  tls:
    termination: passthrough
  to:
    kind: Service
    name: edge
    weight: 100
  wildcardPolicy: None

{{- else }}
{{- with .Values.edge.ingress.nginx }}


{{- if .use_voyager -}}

# with voyager
apiVersion: {{ .apiVersion }}
kind: Ingress
metadata:
  name: edge
  namespace: {{ $.Release.Namespace }}
  annotations:
{{ toYaml .annotations | indent 4 }}
spec:
  rules:
{{ toYaml .rules | indent 4 }}

{{- else }}
# with nginx

apiVersion: {{ .apiVersion }}
kind: Ingress
metadata:
  name: edge
  namespace: {{ $.Release.Namespace }}
  annotations:
{{ toYaml .annotations | indent 4 }}
spec:
  rules:
{{ toYaml .rules | indent 4 }}

{{- end }}

{{- end }} #end with ingress
{{- end }}