kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: edge
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge
      deployment: edge
  template:
    metadata:
      labels:
        app: edge
        deployment: edge
    spec:
      containers:
      - name: edge
        image: {{ tpl $.Values.sidecar.image $ }}
        imagePullPolicy: {{ .Values.sidecar.imagePullPolicy }}
        {{- if .Values.edge.resources }}
        resources:
{{ toYaml .Values.edge.resources | indent 10 }}
        {{- end }}
        env:
    {{- range $envvar := .Values.sidecar.envvars }}
        {{- $envName := $envvar.name | upper | replace "." "_" | replace "-" "_" }}
        {{- if eq $envvar.type "secret" }}
        - name: {{ $envName }}
          valueFrom:
            secretKeyRef:
              name: {{ $envvar.secret }}
              key: {{ $envvar.key }}
        {{- else if eq $envvar.type "value" }}
        - name: {{ $envName }}
          value: {{ tpl $envvar.value $ | quote }}
        {{- end }}
    {{- end  }}
        - name: XDS_CLUSTER
          value: {{ .Values.global.xds.cluster | quote }}
        - name: XDS_HOST
          value: "xds.{{ .Release.Namespace }}.svc.cluster.local"
        - name: XDS_PORT
          value: {{ .Values.global.xds.port | quote }}
        - name: ZK_ADDRS
          value: {{ template "greymatter.exhibitor.address" . }}
        - name: ZK_ANNOUNCE_PATH
          value: {{ .Values.edge.base_path | quote }}
        ports:
        - name: http
          containerPort: 8443
        - name: metrics
          containerPort: 8081
        volumeMounts:
        - name: edge
          mountPath: /etc/proxy/tls/edge
        - name: sidecar
          mountPath: /etc/proxy/tls/sidecar
      imagePullSecrets:
      - name: docker.secret
      volumes:
      - name: edge
        secret:
          secretName: edge
      - name: sidecar
        secret:
          secretName: sidecar
