{{- if .Values.edge.create_edge_secret }}
{{- if .Values.edge.certificates }}
{{- range $name, $cert := .Values.edge.certificates }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $cert.name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
  ca.crt: {{ $cert.ca | b64enc }}
  ca_b64: {{ $cert.ca | b64enc | b64enc }}
  server.crt: {{ $cert.cert | b64enc }}
  cert_b64: {{ $cert.cert | b64enc | b64enc }}
  server.key: {{ $cert.key | b64enc }}
  key_b64: {{ $cert.key | b64enc | b64enc }}
{{- end }}
{{- end }}
{{- end }}
