{{- if and .Values.global.environment (eq .Values.global.environment "openshift") }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: edge
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.global.edge.enableOAuth }}
  host: {{ include "greymatter.domain" . }}
  {{- else }}
  host: {{ include "greymatter.domain" . }}
  {{- end }}
  port: 
    targetPort: proxy
  tls:
    termination: passthrough
  to:
    kind: Service
    name: edge
    weight: 100
  wildcardPolicy: None

{{- else }}
{{- with .Values.edge.ingress }}

apiVersion: {{ .apiVersion }}
kind: Ingress
metadata:
  name: edge
  namespace: {{ $.Release.Namespace }}
  annotations:
{{ toYaml .annotations | indent 4 }}
spec:
  rules:
{{ toYaml .rules | indent 4 }}
{{- end }}
{{- end }}