kind: Service
apiVersion: v1
metadata:
  name: edge
  namespace: {{ .Release.Namespace }}
  labels:
    gmproxy: edge
spec:
  ports:
    - name: proxy
      port: 10808
    - name: metrics
      port: 8081
  selector:
    gmproxy: edge
  sessionAffinity: None
  type: LoadBalancer