{{- if .Values.global.edgeOAuth.enabled }}
{{- if and .Values.global.environment (eq .Values.global.environment "openshift") }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: edge-oauth
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ include "greymatter.domain" . }}
  port: 
    targetPort: proxy
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: edge-oauth
    weight: 100
  wildcardPolicy: None

{{- else }}
{{- with .Values.edgeOAuth.ingress }}

apiVersion: {{ .apiVersion }}
kind: Ingress
metadata:
  name: edge-oauth
  namespace: {{ $.Release.Namespace }}
  annotations:
{{ toYaml .annotations | indent 4 }}
spec:
  rules:
{{ toYaml .rules | indent 4 }}
{{- end }}
{{- end }}
{{- end }}