kind: Service
apiVersion: v1
metadata:
  name: edge
  namespace: {{ .Release.Namespace }}
  labels:
    {{ .Values.global.control.cluster_label }}: edge
spec:
  ports:
    - name: proxy
      port: 10808
    - name: metrics
      port: 8081
  selector:
    {{ .Values.global.control.cluster_label }}: edge
  sessionAffinity: None
  type: