
name: proxy

imagePullSecrets:
  - name: docker.secret

sidecar:
  version: 1.5.0-dev
  image: 'docker.greymatter.io/development/gm-proxy:{{ $.Values.sidecar.version }}'
  port: 10808
  metrics_port: 8081
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  envvars:
    proxy_dynamic:
      type: 'value'
      value: 'true'
    xds_cluster:
      type: 'value'
      value: '{{ .Values.name }}'
    xds_host:
      type: 'value'
      value: 'control.greymatter.svc.cluster.local'
    xds_port:
      type: 'value'
      value: '50000'
    xds_zone:
      type: 'value'
      value: 'zone-default-zone'
