name: proxy

imagePullSecrets:
  - name: docker.secret

global:
  sidecar:
    version: 1.6.2
  spire:
    enabled: true
    trust_domain: quickstart.greymatter.io
    path: '/run/spire/socket/agent.sock'

sidecar:
  version: '{{- $.Values.global.sidecar.version | default "latest" }}'
  image: 'docker.greymatter.io/release/gm-proxy:{{ tpl $.Values.sidecar.version $ }}'
  port: 10808
  metrics_port: 8081
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  envvars:
    proxy_dynamic:
      type: 'value'
      value: 'true'
    xds_cluster:
      type: 'value'
      value: '{{ .Values.name }}'
    xds_host:
      type: 'value'
      value: 'control.default.svc'
    xds_port:
      type: 'value'
      value: '50000'
    xds_zone:
      type: 'value'
      value: 'zone-default-zone'
