dependencies:
- name: catalog
  version: "1.0.3"
  repository: "file://../catalog"

- name: data
  version: "1.0.3"
  repository: "file://../data"

- name: dashboard
  version: "1.0.3"
  repository: "file://../dashboard"

- name: documentation
  version: "1.0.3"
  repository: "file://../documentation"

- name: edge
  version: "1.0.5"
  repository: "file://../edge"

- name: xds
  version: "1.0.2"
  repository: "file://../xds"

- name: exhibitor
  version: "1.0.1"
  repository: "file://../exhibitor"

- name: jwt
  version: "1.0.1"
  repository: "file://../jwt"

- name: slo
  version: "1.0.2"
  repository: "file://../slo"

# This is the Kubernetes ingress controller
- name: voyager
  repository: 'https://charts.appscode.com/stable/'
  version: '10.0.0'
  condition: voyager.enabled