dependencies:
  - name: catalog
    version: '2.0.3'
    repository: 'https://nexus.production.deciphernow.com/repository/helm-hosted'

  - name: data
    version: '2.0.4'
    repository: 'https://nexus.production.deciphernow.com/repository/helm-hosted'

  - name: data
    version: '2.0.4'
    repository: 'https://nexus.production.deciphernow.com/repository/helm-hosted'
    alias: internal-data

  - name: dashboard
    version: '2.0.4'
    repository: 'https://nexus.production.deciphernow.com/repository/helm-hosted'

  - name: edge
    version: '2.0.2'
    repository: 'https://nexus.production.deciphernow.com/repository/helm-hosted'

  - name: jwt
    version: '2.0.3'
    repository: 'https://nexus.production.deciphernow.com/repository/helm-hosted'

  - name: jwt
    version: '2.0.3'
    repository: 'https://nexus.production.deciphernow.com/repository/helm-hosted'
    alias: internal-jwt

  - name: slo
    version: '2.0.6'
    repository: 'https://nexus.production.deciphernow.com/repository/helm-hosted'

  - name: gm-control-api
    repository: 'https://nexus.production.deciphernow.com/repository/helm-hosted'
    version: '2.0.5'

  - name: control
    repository: 'https://nexus.production.deciphernow.com/repository/helm-hosted'
    version: '2.0.2'

  - name: spire
    repository: 'https://nexus.production.deciphernow.com/repository/helm-hosted'
    version: '2.0.1'
    condition: global.spire.enabled
