dependencies:
  - name: catalog
    repository: file://../catalog
    version: '2.1.6'

  - name: data
    repository: file://../data
    version: '2.1.6'

  - name: data
    repository: file://../data
    version: '2.1.6'
    alias: internal-data

  - name: dashboard
    repository: file://../dashboard
    version: '2.1.3'

  - name: edge
    repository: file://../edge
    version: '2.1.6'

  - name: jwt
    repository: file://../jwt
    version: '2.1.1'

  - name: jwt
    repository: file://../jwt
    version: '2.1.1'
    alias: internal-jwt

  - name: slo
    repository: file://../slo
    version: '2.1.2'

  - name: gm-control-api
    repository: file://../gm-control-api
    version: '2.1.6'

  - name: control
    repository: file://../control
    version: '2.1.4'

  - name: spire
    repository: file://../spire
    version: '2.1.1'
    condition: global.spire.enabled
