dependencies:
- name: catalog
  version: "1.0.0"
  repository: "https://nexus.production.deciphernow.com/repository/helm-hosted"

- name: data
  version: "1.0.0"
  repository: "https://nexus.production.deciphernow.com/repository/helm-hosted"

- name: dashboard
  version: "1.0.0"
  repository: "https://nexus.production.deciphernow.com/repository/helm-hosted"

- name: documentation
  version: "1.0.0"
  repository: "https://nexus.production.deciphernow.com/repository/helm-hosted"

- name: edge
  version: "1.0.0"
  repository: "https://nexus.production.deciphernow.com/repository/helm-hosted"

- name: xds
  version: "1.0.0"
  repository: "https://nexus.production.deciphernow.com/repository/helm-hosted"

- name: exhibitor
  version: "1.0.0"
  repository: "https://nexus.production.deciphernow.com/repository/helm-hosted"

- name: jwt
  version: "1.0.0"
  repository: "https://nexus.production.deciphernow.com/repository/helm-hosted"

- name: slo
  version: "1.0.0"
  repository: "https://nexus.production.deciphernow.com/repository/helm-hosted"

