apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent
  namespace: {{ .Values.global.spire.namespace }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
