kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.global.spire.namespace }}.agent
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "nodes"
      - "nodes/proxy"
    verbs:
      - "get"
