kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: greymatter-{{ .Values.global.spire.namespace }}.agent
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
subjects:
  - kind: ServiceAccount
    name: greymatter-agent
    namespace: {{ .Values.global.spire.namespace }}
roleRef:
  kind: ClusterRole
  name: greymatter-{{ .Values.global.spire.namespace }}.agent
  apiGroup: rbac.authorization.k8s.io
