kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.global.spire.namespace }}:agent
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "nodes"
      - "nodes/proxy"
    verbs:
      - "get"
