apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: agent
  namespace: {{ .Values.global.spire.namespace }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
    app: agent
    cluster: spire.agent
spec:
  selector:
    matchLabels:
      app: agent
      {{ .Values.global.control.cluster_label }}: agent
      cluster: spire.agent
  template:
    metadata:
      namespace: {{ .Values.global.spire.namespace }}
      labels:
        {{ .Values.global.control.cluster_label }}: agent
        app: agent
        cluster: spire.agent
        greymatter: spire
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config-configmap.yaml") . | sha256sum | trunc 63 }}
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: agent
      initContainers:
        - name: init-server
          image: {{ .Values.agent.init_image }}
          args:
            - "-t"
            - "30"
            - "server:8443"
        - name: init-registrar
          image: {{ .Values.agent.init_image }}
          args:
            - "-t"
            - "30"
            - "registrar:8444"
      containers:
        - name: agent
          image: {{ .Values.agent.image }}
          args:
            - "-config"
            - "/run/spire/config/agent.conf"
          volumeMounts:
            - name: agent-config
              mountPath: /run/spire/config
              readOnly: true
            - name: agent-socket
              mountPath: /run/spire/socket
              readOnly: false
            - name: server-bundle
              mountPath: /run/spire/bundle
              readOnly: true
            - name: agent-token
              mountPath: /run/spire/token
              readOnly: false
          livenessProbe:
            exec:
              command:
                - /opt/spire/bin/spire-agent
                - healthcheck
                - -socketPath
                - /run/spire/socket/agent.sock
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 3
          {{- if eq $.Values.global.environment "openshift" }}
          securityContext:
            privileged: true
            runAsUser: 0
          {{- end }}
      volumes:
        - name: agent-config
          configMap:
            name: agent-config
        - name: agent-socket
          hostPath:
            path: /run/spire/socket
            type: DirectoryOrCreate
        - name: server-bundle
          configMap:
            name: server-bundle
        - name: agent-token
          projected:
            sources:
              - serviceAccountToken:
                  path: agent
                  expirationSeconds: 7200
                  audience: server
      {{- if (.Values.global.spire.image_pull_secrets) and (ne .Values.global.spire.image_pull_secrets "") }}
      imagePullSecrets:
      {{ toYaml .Values.global.spire.image_pull_secrets | nindent 8 }}
      {{- end }}