{{- $top := . }}
{{- $svidList := list }}
{{- range $name, $service := .Values.global.services }}
    {{- $svidList = append $svidList (print "spiffe://" $top.Values.global.spire.trustDomain "/" $service.serviceName "/mTLS") }}
{{- end }}
{{- $svidList = append $svidList (print "spiffe://" $top.Values.global.spire.trustDomain "/edge/mTLS") }}
{{- $svidList = append $svidList (print "spiffe://" $top.Values.global.spire.trustDomain "/spire-client/mTLS") }}
{{- /* We loop over all the services to create the individual service objects */}}
{{- range $name, $service := .Values.global.services }}
{{- if $service.controlEnabled }}
---
{{/* {{- $lSecret := (default $service.removeListenerSecret false) }} */}}
{{- $serviceExtras := (dict "top" $top "authorizedSvids" $svidList "mTLS" $top.Values.global.spire.enabled "svidList" (toJson $svidList)) }}
{{- $svc := merge $service $serviceExtras }}
{{- $scope := set $top "service" $svc }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-{{.serviceName}}-mesh-config
  namespace: {{ $.Release.Namespace }}
data:
{{- range $path, $bytes := $top.Files.Glob "json/services/**.json" }}
  {{ base $path }}: |-
{{ tpl ($top.Files.Get $path) $scope | indent 4 }}
{{- end }}
...
{{- end}}
{{- end }}
{{- /* Then we loop over the services again in order to create the edge objects */}}
{{- range $name, $service := .Values.global.services }}
{{- if $service.controlEnabled }}
---
{{- $scope := set $top "service" $service }}
{{- $scope = set $scope "mTLS" $top.Values.global.spire.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: edge-{{.serviceName}}-mesh-config
  namespace: {{ $.Release.Namespace }}
data:
{{- range $path, $bytes := $top.Files.Glob "json/edge/**.json" }}
  {{ base $path }}: |-
{{ tpl ($top.Files.Get $path) $scope | indent 4 }}
{{- end }}
...
{{- end}}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-mesh-config
  namespace: {{ $.Release.Namespace }}
data:
{{- range $path, $bytes := $top.Files.Glob "json/special/**.json" }}
  {{ base $path }}: |-
{{ tpl ($top.Files.Get $path) $top | indent 4 }}
{{- end }}
