{{- if .Values.global.control_api_tls }}
{{ if .Values.gmControlApi.ssl.certificates }}
{{- with .Values.gmControlApi.ssl.certificates }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.gmControlApi.ssl.name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
  ca.crt: {{ .ca | b64enc }}
  server.crt: {{ .cert | b64enc }}
  server.key: {{ .key | b64enc }}
{{- end }}
{{- end }}
{{- end }} 