apiVersion: v1
appVersion: 1.0.0
description: A Helm chart to deploy Grey Matter Edge
name: edge
version: 2.2.1
icon: https://s3.amazonaws.com/decipher-public/grey-matter/branding/grey-matter-mark-rgb.png
maintainers:
  - name: Decipher Technology Studios Engineering
    email: engineering@deciphernow.com
    website: deciphernow.com
keywords:
  - Grey Matter
  - service mesh
