{{- if not .Values.jwt.use_aac }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.jwt.users_cg_name }}
  namespace: {{ .Release.Namespace }}
data:
  AOs.json: |-
{{- .Values.jwt.users | nindent 4 }}
  admins.json: |-
{{- .Values.jwt.admins | nindent 4 }}
{{- end }}