kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    {{ .Values.global.control.cluster_label }}: {{ .Values.redis.name | default "redis" }}
  name: {{ .Values.redis.name | default "redis" }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.redis.replica_count  }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{ .Values.global.control.cluster_label }}: {{ .Values.redis.name | default "redis" }}
      deployment: {{ .Values.redis.name | default "redis" }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  progressDeadlineSeconds: 21600
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{ .Values.global.control.cluster_label }}: {{ .Values.redis.name | default "redis" }}
        deployment: {{ .Values.redis.name | default "redis" }}
    spec:
      {{- if .Values.redis.securityContext  }}
      securityContext: {{ toYaml .Values.redis.securityContext | nindent 8 }}
      {{- else }}
      {{- if and .Values.global.environment (or (eq .Values.global.environment "eks") (eq .Values.global.environment "openshift")) }}
      securityContext:
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
      {{- end }}
      {{- end }}
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          {{- if .Values.redis.command }}
          command:
{{ toYaml .Values.redis.command | indent 12 }}
          {{- end }}
          {{- if .Values.redis.args }}
          args:
{{ toYaml .Values.redis.args | indent 12 }}
          {{- end }}
          env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.redis.secret.secret_name }}
                key: password
          imagePullPolicy: {{ .Values.redis.image_pull_policy }}
      {{- if .Values.redis.private_image }}
      imagePullSecrets:
      - name: {{ .Values.global.image_pull_secret }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
