apiVersion: v1
kind: Service
metadata:
  name: catalog
spec:
  selector:
    {{ .Values.global.control_cluster_label }}: catalog
  ports:
    - name: catalog
      port: {{ .Values.catalog.port }}
      targetPort: {{ .Values.catalog.port }}
  type: ClusterIP
  sessionAffinity: None
