apiVersion: v1
kind: Service
metadata:
  name: catalog
spec:
  selector:
    {{ .Values.global.control.cluster_label }}: catalog
  ports:
    - port: {{ .Values.catalog.port }}
      targetPort: {{ .Values.catalog.port }}