apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    {{ .Values.global.control.cluster_label }}: {{ .Values.redis.name }}
  ports:
    - port: 6379
      targetPort: 6379
