kind: StatefulSet
apiVersion: apps/v1
metadata:
  labels:
    {{ .Values.global.control.cluster_label }}: {{ .Values.redis.name }}
  name: {{ .Values.redis.name }}
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ .Values.redis.name }}
  podManagementPolicy: Parallel
  replicas: {{ .Values.redis.replica_count  }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{ .Values.global.control.cluster_label }}: {{ .Values.redis.name }}
      deployment: {{ .Values.redis.name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{ .Values.global.control.cluster_label }}: {{ .Values.redis.name }}
        deployment: {{ .Values.redis.name }}
        greymatter: fabric
    spec:
      {{- if and .Values.global.environment (eq .Values.global.environment "eks") }}
      securityContext:
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
      {{- end }}
      {{- if .Values.redis.private_image }}
      imagePullSecrets:
      - name: {{ .Values.global.image_pull_secret }}
      {{- end }}
      containers:
        - name: redis
          image: {{ tpl .Values.redis.image $ | quote }}
          imagePullPolicy: {{ .Values.redis.image_pull_policy }}
          command:
            - "redis-server"
          args:
            - "--appendonly"
            - "yes"
            - "--requirepass"
            - "$(REDIS_PASSWORD)"
          env:
          {{- include "envvars" (dict "envvar" .Values.redis.envvars "top" $) | indent 12 }}
        {{- if .Values.redis.resources }}
          resources:
{{ toYaml .Values.redis.resources | indent 12 }}
        {{- end }}
          ports:
          - containerPort: 6379
            name: redis
            protocol: TCP
          volumeMounts:
          - mountPath: {{ .Values.redis.storage.mount_path }}
            name: redis-pvc
  volumeClaimTemplates:
  - metadata:
      name: redis-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.redis.storage.size }}Gi
    {{- if .Values.redis.storage.storage_class }}
    {{- if (eq "-" .Values.redis.storage.storage_class) }}
      storageClassName: ""
    {{- else }}
      storageClassName: "{{ .Values.redis.storage.storage_class }}"
    {{- end }}
    {{- end }}
