apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ .Values.global.control.cluster_label }}: {{ .Values.redis.name }}
    deployment: {{ .Values.redis.name }}
spec:
  ports:
    - name: server
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    {{ .Values.global.control.cluster_label }}: {{ .Values.redis.name }}
    deployment: {{ .Values.redis.name }}
