kind: StatefulSet
apiVersion: apps/v1
metadata:
  labels:
    {{ .Values.global.control.cluster_label }}: {{ .Values.redis.name }}
  name: {{ .Values.redis.name }}
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ .Values.redis.name }}
  podManagementPolicy: Parallel
  replicas: {{ .Values.redis.replica_count  }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{ .Values.global.control.cluster_label }}: {{ .Values.redis.name }}
      deployment: {{ .Values.redis.name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{ .Values.global.control.cluster_label }}: {{ .Values.redis.name }}
        deployment: {{ .Values.redis.name }}
        greymatter: fabric
    spec:
      {{- if and .Values.global.environment (eq .Values.global.environment "eks") }}
      securityContext:
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.global.image_pull_secret }}
      containers:
        - name: redis
          image: {{ tpl .Values.redis.image $ | quote }}
          imagePullPolicy: {{ .Values.redis.image_pull_policy }}
          command:
            - "redis-server"
          args:
            - "--appendonly"
            - "yes"
            - "--requirepass"
            - "$(REDIS_PASSWORD)"
          env:
          {{- include "envvars" (dict "envvar" .Values.redis.envvars "top" $) | indent 12 }}
        {{- if .Values.redis.resources }}
          resources:
{{ toYaml .Values.redis.resources | indent 12 }}
        {{- end }}
          ports:
          - containerPort: 6379
            name: redis
            protocol: TCP
          volumeMounts:
          - mountPath: {{ .Values.redis.storage.mount_path }}
            name: redis-pvc
        - name: sidecar
          image: "docker.greymatter.io/development/gm-proxy:latest"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - name: proxy
              containerPort: 10808
            - name: metrics
              containerPort: 8081
          env:
            - name: ENVOY_ADMIN_LOG_PATH
              value: "/dev/stdout"
            - name: PROXY_DYNAMIC
              value: "true"
            - name: XDS_CLUSTER
              value: "{{ .Values.redis.name }}"
            - name: XDS_HOST
              value: "control.default.svc"
            - name: XDS_PORT
              value: "50000"
            - name: XDS_ZONE
              value: "zone-default-zone"
            - name: SPIRE_PATH
              value: /run/spire/socket/agent.sock
          volumeMounts:
            - name: spire-socket
              mountPath: /run/spire/socket
              readOnly: false
      volumes:
      - name: spire-socket
        hostPath:
          path: /run/spire/socket
          type: DirectoryOrCreate
  volumeClaimTemplates:
  - metadata:
      name: redis-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.redis.storage.size }}Gi
    {{- if .Values.redis.storage.storage_class }}
    {{- if (eq "-" .Values.redis.storage.storage_class) }}
      storageClassName: ""
    {{- else }}
      storageClassName: "{{ .Values.redis.storage.storage_class }}"
    {{- end }}
    {{- end }}
