apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ .Values.global.control.cluster_label }}: {{ .Values.redis.name }}
    deployment: {{ .Values.redis.name }}
spec:
  ports:
    - name: proxy
      port: 10808
      protocol: TCP
      targetPort: 10808
  selector:
    {{ .Values.global.control.cluster_label }}: {{ .Values.redis.name }}
    deployment: {{ .Values.redis.name }}
