global:
  control:
    cluster_label: greymatter.io/control
  spire:
    trust_domain: quickstart.greymatter.io
    registration_api_path: /run/spire/socket/registration.sock
    cluster_name: quickstart
    namespace: spire

server:
  image: gcr.io/spiffe-io/spire-server:0.12.0
  config_file_path: /run/spire/config/server.conf
  config_file_dir: /run/spire/config

registrar:
  image: gcr.io/spiffe-io/k8s-workload-registrar:0.12.0
