apiVersion: v2
appVersion: 1.1.1
description: A Helm chart to deploy Grey Matter Service Level Objectives
name: slo
version: 2.1.3
icon: https://s3.amazonaws.com/decipher-public/grey-matter/branding/grey-matter-mark-rgb.png
maintainers:
  - name: Decipher Technology Studios Engineering
    email: engineering@deciphernow.com
    website: deciphernow.com
keywords:
  - Grey Matter
  - service mesh
