global:
  environment: kubernetes
  domain:
  route_url_name:
  remove_namespace_from_url: ''
  exhibitor:
    replicas: 1
  xds:
    port: 18000
    cluster: greymatter

documentation:
  name: documentation
  base_path: '/services/documentation/{{ $.Values.global.documentation.version }}/'
  version: 3.0.1
  image: 'docker.production.deciphernow.com/deciphernow/gm-documentation:v{{ $.Values.global.documentation.version }}'
  imagePullPolicy: Always
  envvars:
    - type: value
      name: base_path
      value: '/services/documentation/{{ $.Values.global.documentation.version }}/'
    - type: value
      name: hidden_content_titles
      value: 'Setup,FAQ'

sidecar:
  version: '{{- $.Values.global.documentation.sidecar.version | default "0.8.0" }}'
  image: 'docker.production.deciphernow.com/deciphernow/gm-proxy:{{ tpl $.Values.sidecar.version $ }}'
  imagePullPolicy: Always
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  envvars:
    service_port:
      type: value
      value: '8080'
    service_host:
      type: value
      value: '127.0.0.1'
    kafka_topic:
      type: value
      value: 'gm-documentation'
    port:
      type: value
      value: '9080'

  # Set this to true if you are attempting to deploy Catalog by itself.
  # Ideally, catalog is deployed as a dependency to Grey Matter, which creates the
  # sidecar secret, but if individual testing is being done, the sidecar secret will
  # need to be created.
  create_sidecar_secret: false
  certificates:
    name: sidecar
    ca: |-
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    cert: |-
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    key: |-
      -----BEGIN RSA PRIVATE KEY-----
      ...
      -----END RSA PRIVATE KEY-----
