global:
  imagePullSecret: docker.secret
  environment: openshift
  domain: staging.deciphernow.com
  route_url_name: greymatter
  remove_namespace_from_url: false
  zone: zone-default-zone
  mesh_tls:
    enabled: true
    use_provided_certs: true
    # This is the DN of the cert being used in the mesh. The Helm charts will add whitelist the DN throughout the mesh
    dn: C=US,ST=Virginia,L=Alexandria,O=Decipher Technology Studios,OU=Engineering,CN=*.greymatter.svc.cluster.local
  # Turns on tls for control api and configures control to talk to it using tls
  control_api_tls: true
  kafka:
    replicas: 3
  dashboard:
    version: 3.3.1
    sidecar:
      version: latest
    sidecar_prometheus:
       version: latest
  catalog:
    version: latest
    sidecar:
      version: latest
  sense:
    enabled: false
  consul:
    enabled: false
    host: ''
    port: 8500
  edge:
    enableTLS: true
    # This is the DN of the new certificate issued to the edge for internal mesh communication. It needs to be whitelisted by the proxies
    egressDn: C=US,ST=Virginia,L=Alexandria,O=Decipher Technology Studios,OU=Engineering,CN=edge
    certPath: /etc/proxy/tls/edge
    version: 1.1.1
  spire:
    enabled: false
  waiter:
    serviceAccount:
      create: false
      name: waiter-sa
  control:
    # This specifies the service name that all XDS clients will try to connect to
    name: control
    port: 50000
    version: latest
  data:
    jwt_prefix: '/jwt'
  internal-data:
    jwt_prefix: '/jwt'
  sidecar:
    version: latest
  
  services:
    catalog:
      egressTLS: true
      mTLS: true
      version: 1.0.3
    dashboard:
      egressTLS: true
      mTLS: true
    prometheus:
      egressTLS: false
      mTLS: true
    data:
      egressTLS: true
      mTLS: true
    internal-data:
      egressTLS: true
      mTLS: true
    jwt:
      egressTLS: true
      mTLS: true
    internal-jwt:
      egressTLS: true
      mTLS: true
    slo:
      egressTLS: true
      mTLS: true
    control:
      egressTLS: false
      mTLS: true
    controlApi:
      # This value must match global.control_api_tls
      egressTLS: true


catalog:
  catalog:
    envvars:
      config_source:
        type: value
        value: 'gmdata'
      config_polling_interval:
        type: value
        value: '30s'
      instance_polling_interval:
        type: value
        value: '5s'
      instance_max_silence:
        type: value
        value: '15s'
      metrics_max_retries:
        type: value
        value: '3'
      metrics_retry_delay:
        type: value
        value: '10s'
      metrics_request_timeout:
        type: value
        value: '15s'
      port:
        type: value
        value: '9080'
      control_server_0_address:
        type: value
        value: '{{ .Values.global.control.name }}.{{ .Release.Namespace }}.svc:{{ .Values.global.control.port }}'
      control_server_0_zone_name:
        type: value
        value: '{{ .Values.global.zone }}'
      control_server_0_request_cluster_name:
        type: value
        value: 'edge'
      use_tls:
        type: value
        value: 'true'
      ca_cert_path:
        type: value
        value: '/etc/pki/ca.crt'
      server_cert_path:
        type: value
        value: '/etc/pki/server.crt'
      server_key_path:
        type: value
        value: '/etc/pki/server.key'
      client_address:
        type: value
        value: localhost
      client_port:
        type: value
        value: '8080'
      client_prefix:
        type: value
        value: '/data'
      client_use_tls:
        type: value
        value: 'true'
      client_cert:
        type: secret
        secret: sidecar-certs
        key: server_b64
      client_key:
        type: secret
        secret: sidecar-certs
        key: key_b64
      client_trust:
        type: secret
        secret: sidecar-certs
        key: ca_b64
      gmdata_startup_delay:
        type: value
        value: '10s'
      gmdata_max_retries:
        type: value
        value: '100'
      gmdata_retry_delay:
        type: value
        value: '5s'
      gmdata_root_event_name:
        type: value
        value: 'world'
      client_identity:
        type: value
        value: 'C=US,ST=Virginia,L=Alexandria,O=Decipher Technology Studios,OU=Engineering,CN=*.greymatter.svc.cluster.local'
      client_email:
        type: value
        value: 'engineering@deciphernow.com'

    init:
      image: 'docker-dev.production.deciphernow.com/deciphernow/gm-proxy:latest'
      envvars:
        debug:
          type: value
          value: 'true'

  sidecar:
    image: 'docker-dev.production.deciphernow.com/deciphernow/gm-proxy:latest'
    create_sidecar_secret: false
    envvars:
      xds_cluster:
        type: value
        value: 'catalog'      
    secret:
      secret_name: sidecar-certs
      mountPoint: /etc/proxy/tls/sidecar
      secretKeys:
        ca: ca.crt
        cert: server.crt
        key: server.key


dashboard:
  dashboard:
    image: 'docker.production.deciphernow.com/deciphernow/gm-dashboard:{{ $.Values.global.dashboard.version }}'
    port: 1337
    # TODO: make these URLs dynamic based on the globally specified version
    fabric_server: '/services/catalog/latest/'
    use_prometheus: 'true'
    objectives_server: '/services/slo/latest/'
    config_server: '/services/gm-control-api/latest/v1.0'
    prometheus_server: '/services/prometheus/latest/api/v1/'
    base_url: '/services/dashboard/{{ $.Values.global.dashboard.version }}/'
    requestTimeout: '15000'
    version: 3.3.1
    imagePullPolicy: IfNotPresent
    secret:
      secret_name: dashboard-certs
      mountPoint: /certs
      secretKeys:
        ca: ca.crt
        cert: service.crt
        key: service.key

  sidecar:
    version: '{{- $.Values.global.dashboard.sidecar.version | default $.Values.global.sidecar.version }}'
    image: 'docker.production.deciphernow.com/deciphernow/gm-proxy:{{ tpl $.Values.sidecar.version $ }}'
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    envvars:
      xds_cluster:
        type: value
        value: 'dashboard'
    secret:
      secret_name: sidecar-certs
      mountPoint: /etc/proxy/tls/sidecar
      secretKeys:
        ca: ca.crt
        cert: server.crt
        key: server.key

  prometheus:
    image: 'prom/prometheus:v2.7.1'
    imagePullPolicy: IfNotPresent
    zk_announce_path: '/services/prometheus/2.7.1'
    version: '2.7.1'
    replica_count: 1
    data_mount_point: /var/lib/prometheus/data
    config_mount_point: /etc/prometheus
    start_cmd: /bin/prometheus
    serviceAccount:
      create: false
      name: prometheus-sa
    #Size is in GB
    pvcSize: 80
    serviceAccount:
      create: false
    resources:
      requests:
        memory: '8Gi'
        cpu: '1'
      limits:
        memory: '12Gi'
        cpu: '2'

  sidecar_prometheus:
    version: '{{- $.Values.global.dashboard.sidecar_prometheus.version | default $.Values.global.sidecar.version }}'
    image: 'docker.production.deciphernow.com/deciphernow/gm-proxy:{{ tpl $.Values.sidecar_prometheus.version $ }}'
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    envvars:
      xds_cluster:
        type: value
        value: 'prometheus'
    secret:
      secret_name: sidecar-certs
      mountPoint: /etc/proxy/tls/sidecar
      secretKeys:
        ca: ca.crt
        cert: server.crt
        key: server.key
          
slo: 
  slo:
    version: 1.1.1
    image: docker.production.deciphernow.com/deciphernow/gm-slo:1.1.1
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    secret:
      secret_name: slo-certs
      mountPoint: /service-certs
      secretKeys:
        ca: ca.crt
        cert: service.crt
        key: service.key

  sidecar:
    version: '{{- $.Values.global.slo.sidecar.version | default $.Values.global.sidecar.version }}'
    image: 'docker.production.deciphernow.com/deciphernow/gm-proxy:{{ tpl $.Values.sidecar.version $ }}'
    metrics_key_function: depth
    imagePullPolicy: IfNotPresent
    secret:
      secret_name: sidecar-certs
      mountPoint: /etc/proxy/tls/sidecar
      secretKeys:
        ca: ca.crt
        cert: service.crt
        key: service.key
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    envvars:
      xds_cluster:
        type: value
        value: 'slo'

  postgres:
    credentials:
      secret_name: postgres-credentials
      username: greymatter
      database: greymatter
    rds:
      enabled: false
      endpoint:
    data_mount_point: /var/lib/pgsql/data
    openshift:
      image: 'docker.io/centos/postgresql-10-centos7'
    k8s:
      image: 'docker.io/centos/postgresql-10-centos7'
    imagePullPolicy: IfNotPresent
    replica_count: 1
    private_image: false
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    confMountPoint: /conf
    # This override is unique to OpenShift's postgresql container
    # https://github.com/sclorg/postgresql-container/tree/master/examples/custom-config
    overridesMountPoint: /opt/app-root/src/postgresql-cfg
    secret:
      secret_name: postgres-ssl-certs
      mountPoint: /certs
      secretKeys:
        ca: ca.pem
        cert: server.crt
        key: server.key
    envvars:
      - type: secret
        name: postgresql_user
        secret: postgres-credentials
        key: username
      - type: secret
        name: POSTGRESQL_PASSWORD
        secret: postgres-credentials
        key: password
      - type: value
        name: POSTGRES_USER_CN
        value: CN=*.greymatter.svc, OU=Engineering, O=Decipher Technology Studios, L=Alexandria, ST=Virginia, C=US
      - type: secret
        name: POSTGRESQL_DATABASE
        secret: postgres-credentials
        key: database