name: Lint and Test Charts

on:
  push:
    branches:
      - '!release-*'


jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Run chart-testing (lint edge)
        id: lint
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: lint
          config: edge-ct.yaml

      - name: Run chart-testing (lint others)
        id: lint
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: lint
          config: ct.yaml
