name: Lint and Test Charts

on:
  push:
    branches:
      - "!release-*"

jobs:
  lint-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Run chart-testing (lint edge and secrets)
        id: lint-edge-secrets
        uses: helm/chart-testing-action@v1.0.0
        with:
          image: quay.io/helmpack/chart-testing:v3.1.1
          command: lint
          config: .chart-testing/edge-secrets.yaml

      - name: Run chart-testing (lint services)
        id: lint-services
        uses: helm/chart-testing-action@v1.0.0
        with:
          image: quay.io/helmpack/chart-testing:v3.1.1
          command: lint
          config: .chart-testing/services.yaml

  lint-umbrella-charts:
    runs-on: ubuntu-latest
    needs: lint-charts
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Run chart-testing (lint fabric sense data)
        id: lint-fabric-sense-data
        uses: helm/chart-testing-action@v1.0.0
        with:
          image: quay.io/helmpack/chart-testing:v3.1.1
          command: lint
          config: .chart-testing/fabric-sense-data.yaml