# This action releases the Grey Matter charts and stores them in
# GitHub on the gh-pages branch, allowing GitHub to host the charts
# instead of depending on Nexus

name: Release Charts

on:
  push:
    branches:
      - release-*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # Install Helm for dependencies
      - name: Install Helm
        uses: azure/setup-helm@v1
        id: install-helm

      - name: Run Grey Matter Charts
        uses: helm/chart-releaser-action@v1.0.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: .

      # We need to release the Fabric Gov chart too. So we just update the Fabric chart
      # and replace the jwt with jwt-gov, then rerun the chart releaser specifically at fabric
      - run: |
          cp -f fabric/Chart.yaml ${{ runner.temp }}/Chart.yaml
          echo "$(awk 'NR==1,/name: jwt/{sub(/name: jwt/, "name: jwt-gov")} 1' fabric/Chart.yaml)" > fabric/Chart.yaml
          sed -i "s|name: fabric|name: fabric-gov|" -e "s|Grey Matter Fabric|Grey Matter Fabric Gov|" -e "s|/jwt|/jwt-gov|" fabric/Chart.yaml

      - name: Release Fabric Gov Chart
        uses: helm/chart-releaser-action@v1.0.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: fabric

      - run: mv ${{ runner.temp }}/Chart.yaml fabric/Chart.yaml


