# This action releases the Grey Matter charts and stores them in
# GitHub on the gh-pages branch, allowing GitHub to host the charts
# instead of depending on Nexus

name: Release Charts

on:
  push:
    branches:
      - release-*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # Install Helm for dependencies
      - name: Install Helm
        uses: azure/setup-helm@v1
        id: install-helm

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: .