apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.control.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.control.replicas }}
  selector:
    matchLabels:
      gm.proxy: {{ .Values.control.name }}
      deployment: {{ .Values.control.name }}
  template:
    metadata:
      labels:
        gm.proxy: {{ .Values.control.name }}
        deployment: {{ .Values.control.name }}
        run: {{ .Values.control.name }}
    spec:
      # This service_account must have read access to both pods and endpoints, because gm-control uses the kubernetes API to do service discovery, and the waiter init container needs access to service endpoints to wait on control-api
      serviceAccountName: {{ .Values.control.service_account.name }}
      containers:
        - name: {{ .Values.control.name }}
          image: {{ tpl .Values.control.image $ }}
          imagePullPolicy: {{ .Values.control.image_pull_policy }}
          env:
            {{- include "envvars" (dict "envvar" .Values.control.envvars "top" $) | indent 10 }}
          ports:
            - name: grpc
              containerPort: {{ .Values.global.control_port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: grpc
            initialDelaySeconds: 2
          resources: {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.control.secret }}
          volumeMounts:
            - name: controlapi-certs
              mountPath: {{ .Values.control.secret.mount_point }}
        {{- end }}
      initContainers:
        - name: ensure-control-api
          image: {{ .Values.global.waiter.image }}
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: SERVICE
              value: control-api
            - name: POST_DELAY
              value: '10'
      imagePullSecrets:
      - name: {{ .Values.global.image_pull_secret }}
      {{- if .Values.control.secret }}
      volumes:
        - name: controlapi-certs
          secret:
            secretName: {{ .Values.control.secret.secret_name }}
            defaultMode: 0777
      {{- end }}