apiVersion: v1
kind: Service
metadata:
  labels:
    run: {{ .Values.control.name }}
    {{ .Values.global.control_cluster_label }}: {{ .Values.control.name }}
  name: {{ .Values.control.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.global.control_port }}
    protocol: TCP
    targetPort: grpc
  selector:
    run: {{ .Values.control.name }}
  type: ClusterIP
